dateutil/dateutil

- dateutil/parser.py
Adds explicit error checking when AM or PM are specified. `dateutil.parser.parse()` will now raise a `ValueError` exception if either AM or PM is specified without specifying an hour, or when the hour specified is outside the range `1 <= hour <= 12`, since AM/PM indicates a 12-hour clock. This resolves issue #21.
> Add explicit error checking along with AM/PM flag.

- dateutil/parser.py
Looking at how this was parsed from ReadTheDocs, I guess it's using restructuredText not markdown, my mistake. This fixes the part that was actually parsed. The documentation that didn't make it into readthedocs can be a later update.
> Markdown -> RST.

- README.rst
- dateutil/test/test.py
Documentation currently uses `parse()` for almost all the rrule tests, and a bunch of others. I think it's better to explicitly specify `datetime` objects, since any problems with the parser will start causing the rrule tests to fail as well, causing the tests to be less well-separated. It also probably speeds up the test process a bit.
> Doc and test tweaks

- dateutil/parser.py
Simple documentation fix to the parser - all the parameters were documented on private methods only!
Would like to eventually add something to allow transclusion of these parameters, but this should work for now.
> Add parameters to public methods in parser.

- dateutil/relativedelta.py
- dateutil/test/test.py
Python 3 implements truth-testing by, among other things, calling the [`__bool__`][1] method of a class instance, whereas Python 2 calls the [`__nonzero__`][2] method. dateutil.relativedelta only implements `__bool__`, which means that for example:
``` python
>>> bool(relativedelta(days=0))
True
```
There's already an open [issue][3] for this on launchpad, with a fix.
This pull-request introduces a failing test.
[1]: https://docs.python.org/3/library/stdtypes.html#truth
[2]: https://docs.python.org/2/library/stdtypes.html#truth
[3]: https://bugs.launchpad.net/dateutil/+bug/1035038
> Boolean evaluation of relativedeltas on python 2.7

- dateutil/rrule.py
I decided that at least for now, it's best not to keep these as sets. Although we're under no particular API obligations to maintain the data types of internal variables, I don't think the speedup is particularly dramatic, and I know there's code out there relying on the fact that these are stored as slicable iterables (e.g. #50 and #24) and I'm afraid that having a consistent order might be important for some things as well.
If the data set is going to change, we can hold that off for `rrule2`, which will be rearranging the internal structure of rrule dramatically anyway.
This also fixes one bug in the `__construct_byset` method that I found (albeit one that is currently unreachable).
> Changed internal rrule._byxxx variables back to tuples (now sorted). 

- dateutil/parser.py
- dateutil/test/test.py
Fixes issue #51. I was a bit hesitant to wade into character encodings, which seem like they can be very complicated if not done right, but the same strategy is used successfully in `parser.parse()`, so I think it's fine.
> Fix issue with tzstr parsing on Python 2.x. lp:1331576, gh #51

- dateutil/rrule.py
- dateutil/test/test.py
Adds an `xafter` method to `rrule`, which is a generator function generating all recurrences after a specified date.
An equivalent `xbefore` method is not simple to implement, as it is not possible to iterate backwards through an `rrule`. That may be a nice enhancement for `rrule2` if possible.
> Add xafter method to rrule

- dateutil/parser.py
- dateutil/test/test.py
Fix fuzzy parsing issue with AM/PM flag. This should solve #56 (LP [1428895](https://bugs.launchpad.net/dateutil/+bug/1428895)) - as well as the related issue that strings like, "Meet me at 3AM at the AM/PM" would be parsed as 3 PM (because "PM" was the most recent flag raised).
> Fix AM/PM flag issue with fuzzy parser

- dateutil/zoneinfo/__init__.py
This function was removed from the zoneinfo module in version 2.3 and
causes an error when doing a wildcard import from the zoneinfo module.
```python
>>> from dateutil.zoneinfo import *
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'setcachesize'
```
> Remove 'setcachsize' from zoneinfo __all__ list

- dateutil/parser.py
- dateutil/test/test.py
Addresses Issue #25, but does not change the default behavior of the parser. This adds a `smart_defaults` option to the parser, along with a corresponding `date_in_future` option.
I have also added the option `fallback_on_invalid_day`, which silently corrects the date to the end of the month if a date outside of the valid range is provided. Thus you can use the default automatic-replacement behavior while still allowing no error to be thrown in the event of a conflict in month lengths.
@jarondl, @Allactaga @umrashrf Any issues with this approach?
> Add smart defaults and fallback options to parser.

- NEWS
I know that the typo is in the commit message as well, but I figure that this is a description of the changes made.
> Fixed typo in NEWS

- dateutil/parser.py
- dateutil/test/test.py
For certain test cases, using `with_fuzzy_tokens=True` will cause parse to fail because a tuple is expected to be returned by _parse. This is then incorrectly unpacked which results in a confusing TypeError message. The standard way would be to allow a ValueError to be thrown. 
Example of issue:
>> import dateutil.parser
>> dateutil.parser.parse('04/04/0d4', fuzzy_with_tokens=True)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "dateutil/parser.py", line 1139, in parse
return DEFAULTPARSER.parse(timestr, **kwargs)
File "dateutil/parser.py", line 452, in parse
res, skipped_tokens = self._parse(timestr, **kwargs)
TypeError: 'NoneType' object is not iterable
This pull request solves this issue for cases similiar to those specified in the test included (and any …
> Fail correctly when using with_fuzzy_tokens and incorrect strings

- dateutil/zoneinfo/__init__.py
- dateutil/zoneinfo/rebuild.py
- updatezinfo.py
bugfix #97 
Fix for an issue that happens inside GAE sandbox, where `subprocess.check_call` is not available.
> Extract tz rebuild into separate file

- dateutil/tzwin.py
Stop encoding `_dstname` and `_stdname` to bytes with `iso-8859-1`, because we cannot assume that's the
correct codepage. Uses the current solution we use in `tz.py`, which outputs unicode in Python3.
Fixes #92  and http://stackoverflow.com/questions/21296475/python-dateutil-unicode-warning
and https://bugs.launchpad.net/dateutil/+bug/1227221
> Fix tzwin encoding errors

- dateutil/tz.py
Currently the `_std_offset` and `_dst_offset` are one-off set during module import using the timezone info from `time.timezone`.
For many users especially Django users (Django set timezone info according to TIME_ZONE setting), the time.timezone may change when you set environment variable `os.environ['TZ']` and call `time.tzset()` (ref: https://docs.python.org/2/library/time.html#time.tzset).
Therefore, new instances created by `dateutil.tz.tzlocal()` should be able to reflect this change, i.e., the timezone offset should not be fixed at the import time.
Use the following code to reproduce the issue:
```
from dateutil import tz
import time
import os
print time.timezone
print tz.tzlocal()._std_offset
os.environ['TZ'] = 'Etc/UTC'
time.tzset()
print time.timezone
print …
```
> Initialize `_std_offset` and `_dst_offset` per tzlocal instance

- dateutil/parser.py
Fix inaccurate documentation - fixes #80.
Also I've adjusted the formatting of the docs. There's still some significant repetition of text here, it would be best to figure out the right way to transclude that information so it can be more easily updated, but I'll leave that for a later fix.
> Tzinfo docfix

- dateutil/parser.py
- dateutil/test/test.py
By default, the Python logging module uses a format that includes `%(asctime)s`. The Python docs define this variable as:
Human-readable time when the LogRecord was created. By default this is of the form ‘2003-07-08 16:49:45,896’ (the numbers after the comma are millisecond portion of the time).
Example: `2003-09-25 10:49:41,502`
Currently, dateutil fails to parse a string like this:
```python
>>> from dateutil.parser import parse
>>> parse("2003-09-25 10:49:41,502")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 1008, in parse
return DEFAULTPARSER.parse(timestr, **kwargs)
File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 395, in parse
raise ValueError("Unknown string …
```
> Parse python logger timestamps

- dateutil/relativedelta.py
- dateutil/test/test.py
relativedelta forgets about microseconds when comparing.
> relativedelta: Do not forget to compare microseconds

- tox.ini
This fixes testing under Tox and matches the behaviour of Travis
> Tox: install unittest2 under Python 2.6

- dateutil/tz.py
- dateutil/tzcommon.py
- dateutil/tzwin.py
Exported `tzname_in_python2` into another file `tzcommon.py` and imported it in `tz.py` and `tzwin.py`
> Hotfix-133: Fix tzwin.py not importing when needed on Windows

- setup.py
@pganssle could only find the launchpad version before.  Merging this and tagging a new release should fix the pip problem
```
(/tmp/dummy)tcaswell@edill-810g:~$ pip install dateutil
Collecting dateutil
Could not find a version that satisfies the requirement dateutil (from versions: )
No matching distribution found for dateutil
(/tmp/dummy)tcaswell@edill-810g:~$ python --version
Python 3.5.1 :: Continuum Analytics, Inc.
```
> BLD: update versions of python supported

- docs/rrule.rst
The [source docstring](https://dateutil.readthedocs.org/en/latest/_modules/dateutil/rrule.html#rrule) already has the description and due to this there is a redundancy in the [docs](https://dateutil.readthedocs.org/en/latest/rrule.html#rrule). I dint want to mess with source code, hence i thought about removing the extra line from the docs. 
>This is my first contribution to open source, do let me know if I am doing anything wrong in here.
> removed redundant description in rrule description

- .travis.yml
- appveyor.yml
- ci_tools/retry.bat
- ci_tools/retry.sh
A partial mitigation of #176, adding retry logic to the `updatezinfo.py` script.
A next step (not necessarily to be done before the 2.5.0 release (#169) is to host our own mirror of all the tzdata files on HTTPS. I suspect part of the issue might be that we're downloading over ftp, which seems to be a bit finicky when I played with it using `ftplib`.
> Retry logic for travis and appveyor

- setup.py
https://docs.python.org/3/distutils/setupscript.html#listing-whole-packages
> added 'dateutil.tz' subpackage to setup.py

- dateutil/test/test_tz.py
- dateutil/tz/tz.py
Fixes #132. I don't think the tests here are compatible with the #180 stack because I changed how `dateutil.tz` is imported, so when those are merged, I'll rebase and clean up.
> Add tzinfo compatibility with non-datetime times

- updatezinfo.py
- zonefile_metadata.json
I've created a mirror of the IANA database on a [github pages repository](https://dateutil.github.io/tzdata/). This is the first step in having a separate update channel between the code and the tzdata files. For now, having an HTTPS mirror of the tzdata tarball should help to further alleviate the CI failure issues.
> Bump metadata version to 2.0, add support for tzdata mirrors.

- dateutil/test/test_tz.py
- dateutil/tz/tz.py
- dateutil/tz/win.py
This is a combination of PRs #179 and #180 because of some funkiness with the rebase that was muddying up the git history. It fixes Issues #148 and #151.
Built off #178 for convenience, this adds `__repr__` functionality to `tzwinlocal()`. The 'StandardName' will be used for all repr (this does not affect tzname()).
Fixes #148.
I will note that even if the tzwin objects are identical on all relevant characteristics (i.e. they represent the exact same offset at all times), they will compare unequal if their names are different. Not sure how I feel about this, but it seems like the best way to go in terms of least surprise.
Fixes #151.
> Add REPR and comparison functionality to tzwinlocal

- dateutil/parser.py
- dateutil/test/test.py
Rolling back `smart_defaults` and `fallback_on_invalid_date` introduced in PR #30, My explanation for this is found in Issue #169:
> In the time since adding this, I've been thinking we may want to implement this differently, and I don't want to get stuck maintaining API compatibility. (This should automatically fix #126 for the release, but that should also be updated on the feature branch). I think this should be re-implemented with a combination of #125 and breaking up `parse` into smaller, customizable functions.
Since these features have not been included in a public release yet, hopefully it will not break anyone's dependencies here.
> Rolled back smart_defaults and fallback_on_invalid_dates modifications to parser

- MANIFEST.in
Ensure binary, compiled files and cache directories are not included in generated source distributions (sdist)
While I'm here, tweak include directive for tests to ensure all test/ directory files are included in the future, no matter what extension they have
See https://github.com/dateutil/dateutil/commit/f6b45501f41f74bf9579606d5ff87587f48f9fe4 commit comments
> Add __pycache__ & py[co] exclusions to MANIFEST.in

- dateutil/tz/__init__.py
- dateutil/tz/_common.py
- dateutil/tz/tz.py
- dateutil/tz/win.py
This adjusts the import scheme for `tz` per the discussion in PR #202 (which solves pyinstaller/pyinstaller#1848). See the discussion there with @htgoebel.
This scheme is closer to the one originally implemented in @labrys's PR.
> Rearrange .tz module to fix import error

- dateutil/rrule.py
- dateutil/test/test_rrule.py
Fixes #104.
I also took bit of time to improve the code coverage in the rrule module, and to break up the monolithic test case a bit (though it can still stand to be broken up more).
Likely the weekday tests will be moved when #140 is implemented.
> Fix rruleset cache

- dateutil/tz/win.py
This should address the reported issue from Sickrage/sickrage-issues#1098, reported by @labrys.
I have only been able to test this on a US locale so far, and I have no idea how to set up Appveyor to switch to a locale with unicode time zones. I'd love to get that set up, though, since we've had these testability issues before.
> Changed key retrieval to unicode string.

- dateutil/rrule.py
- docs/examples.rst
Resolves #105 and #149.
I've added an explicit note to the `rrule` documentation indicating the possibly surprising behavior of rrules where `dtstart` is at the end of the month. I've also (hopefully) clarified the `until` parameter's documentation and added a note about the deprecation of using `count` along with `until`.
When I was testing the new rrule doctest, I also noticed a few parser doctests that were failing. They fail at least as far back as version 2.2, so I'm assuming the behavior of `parser` changed between the time the docs were written and 2.2. Rather than try and change the behavior back (not sure why we'd want to - the behavior exhibited in the docs was kinda surprising), I just updated the doctests.
> Adjustments to rrule documentation

- dateutil/relativedelta.py
- dateutil/test/test_relativedelta.py
I've improved the test coverage on the `relativedelta` module, and while I was in there I did some refactoring to make the code a bit more readable.
I should note that I did not add any tests for the `weekday` objects, because that already has good test coverage in the `rrule` module, and will eventually be moved into a common file to prevent code duplication.
I also deliberately didn't add a test for [this `TypeError`](https://github.com/dateutil/dateutil/blob/master/dateutil/relativedelta.py#L131) - I think it is considered an antipattern to explicitly check inheritance like that (rather than duck-typing), so I didn't want to "endorse" this behavior that may go away.
> Refactor relativedelta a bit, improve test coverage.

- dateutil/test/test_tz.py
- dateutil/tz/win.py
> Allow tzwin objects to work with tzinfo

- MANIFEST.in
Fix typo: `s/dateutils/dateutil/`, also trailing `/` was causing this to not work.
> Fix issue with MANIFEST.in test inclusion.

- NEWS
- dateutil/__init__.py
Prepare the 2.5.2 version release (mostly coinciding with the `tzdata2016c` release).
> Prepare 2.5.2 release.

- dateutil/rrule.py
- dateutil/test/test_rrule.py
Hi,
I've added replace method for creating new rrule with modified attributes. It is inspired by replace methods in python datetime library.
> New rrule.replace method to create new rrule with modified attributes

- dateutil/rrule.py
I noticed that on Python 2.x, the test performance was abysmal for whatever reason, taking MUCH longer than the Python 3.x tests.  Using [nose-timer](https://github.com/mahmoudimus/nose-timer), I determined that the issue was the `rrule` tests:
```
[master@dateutil]$ python2 `which nosetests` --with-timer --timer-top-n 10
... [clipped] SSSS
dateutil.test.test_rrule.RRuleTest.testToStrSecondlyByWeekNoAndWeekDay53: 0.9731s
dateutil.test.test_rrule.RRuleTest.testToStrSecondlyByWeekNo: 0.5110s
dateutil.test.test_rrule.RRuleTest.testSecondlyByWeekNoAndWeekDay53: 0.4850s
dateutil.test.test_rrule.RRuleTest.testToStrSecondlyByMonthAndYearDayNeg: 0.4731s
dateutil.test.test_rrule.RRuleTest.testToStrSecondlyByEasterPos: 0.4554s
dateutil.test.test_rrule.RRuleTest.testToStrSecondlyByEaster: 0.4549s …
```
> Significantly improve rrule performance on Python 2.x

- dateutil/relativedelta.py
- dateutil/test/_common.py
- dateutil/test/test_relativedelta.py
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
- dateutil/tz/win.py
The [Python documentation](https://docs.python.org/3.5/library/constants.html) indicates that `NotImplemented` should be returned for rich comparison and arithmetic operations on defined classes. Up until now, we've been raising `TypeError` or returning `False` automatically, which prevents less picky classes from properly implementing operations with respect to our classes.
I think this covers all the operators we define.
> Use NotImplemented in defined classes.

- dateutil/parser.py
- dateutil/test/test_parser.py
Fixes #171. Now rather than failing with `AttributeError` when passed an invalid type, the parser should fail with `TypeError`.  Valid types are anything that implements a `read` method.
> Throw TypeError on non-character non-stream types.

- dateutil/test/_common.py
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
Among other improvements, this adds fold support to `tz.tzlocal()`. I have not tested this behavior on Windows because I don't think windows supports the POSIX-style assignment of the `TZ` variable.
There is also a behavior change with regard to bare `time` objects - `tzlocal()` can now be used to create timezone-aware `time()` objects if your local time zone has a fixed offset.
Since a date is required to resolve the ambiguity in non-fixed-offset times, that still returns `None`.
Finally, I also did some refactoring on the tests. Slowly but steadily, I'm managing to break up the monolithic `TzTest` object.
> Add ambiguous time support to tzlocal()

- dateutil/rrule.py
- dateutil/test/test_rrule.py
This fixes #262 by converting `wkst` to a weekday string when stringifying an rrule.
> Format wkst properly in rrule.__str__

- codecov.yml
Codecov right now is updating the webhooks before both CIs comes in, and isn't waiting for both. This _should_ fix that.
I can't seem to get it to stop commenting, or restrict to status-only requirements, but I guess that's not critical.
> Explicitly added both CI builds.

- README.rst
- RELEASING
- setup.py
As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- dateutil/test/test_tz.py
- dateutil/tz/tz.py
This PR is not ready for merging, I just want to fire off the CI as I work on it. This will resolve #249. 
So far it includes:
* Improved documentation for many classes in the `tz` module.
* Fold support for `tzstr`, `tzrange` and `tzlocal`.
* Improved test coverage for `tzical`
Before merging, the following still needs to be done:
Deferring these two:
-  <strike>Documentation for `tzfile`</strike>
- <strike>Implementation of #253 </strike>
I will also possibly implement #260, depending on how it's best to implement #253.
> Full ambiguous timezone support.

- dateutil/relativedelta.py
- dateutil/test/test_relativedelta.py
In response to issue #282. I played with it in the context I first noticed it and everything seems fine.
> Allow datetime.timedelta to be added to relativedelta

- dateutil/relativedelta.py
- dateutil/tz/tz.py
I've been working through looking at adopting Python 3, and I've been utilizing the -3 flag to help idenitfy issues with Python 3.
Here's a quick write up I did last week:
https://gist.github.com/rowillia/c0feed97c1863b2d8e5a3ed73712df65
The -3 flagged a few issues in dateutil worth fixing, namely around __eq__ shadowing __hash__ in PY3.
Fixing these issues will help make the -3 flag less noisey for folks running dateutil in production.
> Fix some Python 3 issues flagged by the -3 flag

- .travis.yml
- README.rst
- appveyor.yml
- ci_tools/pypy_upgrade.sh
It seems that something related to #302 is causing only old versions of pypy to fail, and travis only supplies old versions. This change will make pypy3 passing optional (no newer version is available) and forces an upgrade in travis.
There is also some sort of issue in Appveyor where the pip command isn't being found in the path for the right version of Python for some reason. This PR explicitly uses the right version of pip.
This also addresses #287.
> Tweak CI due to version inconsistencies and other issues.

- dateutil/test/test_tz.py
- dateutil/tz/_common.py
- dateutil/tz/tz.py
- dateutil/tz/win.py
- tox.ini
This fixes #284 and #286 and adds Python 3.6 to the `tox.ini` to test the ability to fall back to real "fold" functionality.
This also adds the `is_ambiguous(dt)` function to all `_tzinfo` subclasses, and exposes the `enfold` function for backwards compatibility purposes, which is a first crack at #253.
> Implement PEP495 for all tzinfo objects.

- dateutil/test/test_tz.py
- dateutil/tz/tz.py
Thought I had already added this feature. This allows `tzoffset` to be constructed from a `timedelta`.
> Added support for timedelta objects when constructing tzoffsets

- .travis.yml
Python 3.6 is particularly important in this case because of the code paths with differences due to PEP-495 support.
> Add 3.6-dev and nightlies as allowed-fail build targets in travis.

- dateutil/test/test_tz.py
- dateutil/tz/tz.py
> Prevent improper behavior when a tzfile is attached to a datetime.time object.

- dateutil/test/test_tz.py
- dateutil/tz/_common.py
- dateutil/tz/tz.py
- dateutil/zoneinfo/__init__.py
Per #11, this deprecates `dateutil.zoneinfo.gettz()`. The new workflow is to generate a `ZoneInfoFile` instance and use `ZoneInfoFile.get` to retrieve time zones.
A new method, `zoneinfo.get_zonefile_instance()` is provided to make it easier to get the old "singleton" behavior.
> Deprecated zoneinfo.gettz and added new preferred method.

- dateutil/_common.py
- dateutil/easter.py
- dateutil/relativedelta.py
- dateutil/rrule.py
- dateutil/tz/tz.py
- dateutil/tz/win.py
- dateutil/zoneinfo/__init__.py
Last minute documentation fixes, also fixed the zonefile `__all__` so that the replacement command for `gettz()` is actually exposed.
At some point in the future we should also expose the `ZoneInfoFile` class itself to let people instantiate vs. their own streams, but I think that can be left for version 2.7.0.
> Expose zoneinfo instance and other documentation fixes.

- dateutil/tz/__init__.py
- dateutil/tz/_common.py
`tz.enfold`, `tz.datetime_ambiguous` and `tz.datetime_exists` are not currently in the documentation because they were not added to `tz/__init__.py:__all__`. This fixes that.
> Added new tz methods to documentation.

- dateutil/rrule.py
- dateutil/test/test_rrule.py
Replaced any `if count` to `if count is None`.
Where count is checked to stop iteration, moved the check before an item is yielded, and updated the predicate so that it will still yield the correct results.
Added a test for when count is zero.
Closes #329
> Handles cases where count parameter is 0

- dateutil/parser.py
- dateutil/test/test_parser.py
Fuzzy-parsing drops tokens in cases where a token is initially assessed with val_is_ampm==True (line 941) and later determined not to be (line 950).  A motivating example:
>>> dateutil.parser.parse('http://biz.yahoo.com/ipo/p/600221.html', fuzzy_with_tokens=True)[1]
(u'http://biz.yahoo.com/ipo/', u'/', u'.html')
This pull request prevents the "p" from being dropped, so this becomes:
>>> dateutil.parser.parse('http://biz.yahoo.com/ipo/p/600221.html', fuzzy_with_tokens=True)[1]
(u'http://biz.yahoo.com/ipo/p/', u'.html')
> Append to skipped_tokens when not val_is_ampm

- setup.py
With warnings turned on, appears as:
```
setup.py:17: ResourceWarning: unclosed file <_io.BufferedReader name='./dateutil/__init__.py'>
```
> Fix unclosed file warning in setup.py

- dateutil/test/test_parser.py
As the file contains `from __future__ import unicode_literals`, the bare
string is already a unicode object. No need to coerce it. Further, it
can always be converted to a bytes object with `.encode()`, no need to
catch `NameError`.
> Remove unnecessary coerce to unicode/bytes code

- dateutil/test/test_relativedelta.py
- dateutil/test/test_rrule.py
The two `testToStrYearlyByMonth` tests were functionally identical, so I
combined them into one.
The other tests used slightly different test data, so kept both
instances, but could also delete one if preferred.
> Avoid duplicate test names

- dateutil/parser.py
- dateutil/test/test_imports.py
- dateutil/test/test_rrule.py
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
F841 local variable `name` is assigned to but never used
Now use seek to skip over lzh_leapcnt pairs in tz.py. As the values are
unused, no need to read them and convert them to Python objects. It is
only wasted cycles and memory. Skip over with seek() instead.
Rewrote testTzwinStar based on surrounding similar tests. Previous
version did not achieve an interesting result.
I believe non of the removals have intended side effects, If I'm
mistaken, please let me know.
> Fix all instances of flake8 F841

- dateutil/relativedelta.py
- dateutil/rrule.py
- dateutil/test/test_parser.py
- dateutil/test/test_tz.py
- dateutil/tz/_common.py
- dateutil/tz/tz.py
- E301 expected 1 blank line, found X
- E303 too many blank lines (X)
https://pep8.readthedocs.io/en/latest/intro.html#error-codes
> Fix all instances of flake8 E301 & E303

- dateutil/rrule.py
Simple fix, that changes the wording of one exception, that can be misleading
> Fix copy/paste typo in rrulestr

- dateutil/rrule.py
- dateutil/test/_common.py
- dateutil/tz/_common.py
- dateutil/tz/tz.py
- dateutil/tz/win.py
- updatezinfo.py
Brings code closer to flake8 compliance by passing rule:
E305 expected 2 blank lines after class or function definition
http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
> Use 2 spaces after top level definitions

- dateutil/parser.py
- dateutil/test/test_parser.py
- dateutil/test/test_rrule.py
- dateutil/test/test_tz.py
- dateutil/tz/_common.py
- dateutil/tz/tz.py
- dateutil/tz/win.py
- dateutil/zoneinfo/__init__.py
Discovered using flake8. If you'd like, I can add routine flake8 testing
to the CI configuration to prevent new unused imports.
> Clean up unused imports

- dateutil/parser.py
- dateutil/test/test_parser.py
Possibly a fix for issue #343 
Issue summary: Short day names had to be at least 3 characters long to be recognized, which works for the default day names (`Mon`, `Tue`, ...) but not necessarily for custom `WEEKDAYS` names such as German day name abbreviations (`Mo`, `Di`, ...).
* This PR changes the check from a comparison against a constant value (`3`) to a value calculated from the entries of the `WEEKDAYS` setting. 
* Since the same applies to `MONTHS`, applying the equivalent change there. 
* Added a test for the case of German day names, which fails before the change and passes after.
A possible next step would be to cache the return value of `min(len(n) for n in self._weekdays.keys())` to avoid re-computation. Please let me know if that would be preferred here.
> Allow for two day names shorter than 3 letters (#343)

- dateutil/tz/_common.py
- dateutil/tz/tz.py
One of a few improvements intended to improve the speed of these `tzinfo` objects. `tzutc` and `tzoffset` are purely static offsets, so there's no need to go through the whole `fromutc` function, given that we're implementing it in pure python in `_tzinfo` anyway.
> Fast track fromutc

- .travis.yml
- appveyor.yml
- dateutil/test/test_tz.py
All the original fold and gap tests were written for an intermediate version of `tz` that stored state in the `tzinfo` object, which was abandoned to better be compliant with PEP-495, this PR cleans up a lot of that and also tests that these objects comply with the PEP-495 equality semantics (for the most part).
I've also merged in #365 here, because this fixes the `tzwin` tests so that they work properly with Python 3.6.
> Fix tz fold tests

- dateutil/parser.py
- dateutil/test/test_parser.py
Fixes #333. Still not 100% sure if the `i += 1` that was never being reached is strictly necessary, but I think that that is supposed to advance the tokens properly. Not entirely sure why the values were already being advanced properly, but all the tests seem to pass, so I think we're good. 
cc: @jbrockmendel @mrForce
> Fix improper indent in parser.

- dateutil/test/test_parser.py
- dateutil/test/test_relativedelta.py
- dateutil/test/test_rrule.py
Fixes all flake8 error F405:
F405 'parse' may be undefined, or defined from star imports: dateutil.parser
> Replace all star imports with explicit imports

- .travis.yml
- NEWS
- dateutil/parser.py
- dateutil/rrule.py
- dateutil/test/_common.py
- dateutil/test/test_easter.py
- dateutil/test/test_imports.py
- dateutil/test/test_parser.py
- dateutil/test/test_relativedelta.py
- dateutil/test/test_rrule.py
- dateutil/test/test_tz.py
- dateutil/tz/_common.py
- dateutil/tz/tz.py
- dateutil/tz/win.py
- dateutil/zoneinfo/__init__.py
- dateutil/zoneinfo/rebuild.py
- setup.py
- tox.ini
I would humbly like to suggest dateutil drop support for Python 2.6.
The last release of Python 2.6 was 2013-10-29, over 3 years ago. It is
no longer receiving security fixes.
https://www.python.org/dev/peps/pep-0361/
The pip project itself has recently dropped support for 2.6. Their
numbers estimate that Python 2.6 accounts for ~2% of their downloads.
pypa/pip#4343
For projects that still use Python 2.6, they can continue to pip install
an older version.
I've tried my best to remove as much 2.6 specific code as I can,
including the 'Programming Language :: Python :: 2.6' trove classifier
from setup.py. I've also removed Travis CI testing, which should result
in faster testing and fewer wasted resources.
Code changed:
- Removed Python2.6 from testing configuration
- setup.py cleanups due …
> Drop support for Python 2.6

- dateutil/_common.py
- dateutil/relativedelta.py
- dateutil/test/test_relativedelta.py
This builds on https://github.com/dateutil/dateutil/pull/296 by making those classes hashable by explicitly providing the `__hash__` method
classes touched:
- relativedelta
- weekday
> Make classes hashable 

- dateutil/parser.py
helpful if exeption is catched above for displaying instead of being blind, e.g. diagnosting broken vcalendar items:
```
vobject.base.ParseError: "In transformToNative, unhandled exception on line None: <class 'ValueError'>: ('Unknown string format:', '1970DTSTART:19700329T020000')"
vobject.base.ParseError: "In transformToNative, unhandled exception on line None: <class 'ValueError'>: ('Unknown string format:', '19701TZOFFSETFROM:-0000')"
```
(don't ask how such entries can occur...)
> add rejected timestr in exception message providing more information to caller

- dateutil/parser.py
- dateutil/test/test_parser.py
In the status-quo, [L824-825](https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py#L824) checks:
```
if i < len_l and l[i] == ':':
res.second, res.microsecond = _parsems(l[i+1])
```
Avoiding an IndexError requires checking `i+1 < len_l`.  This is easy to miss because the try/except catches IndexError.  One way to trigger this is:
```
import dateutil.parser
dateutil.parser.IndexError = SyntaxError
dateutil.parser.parse('2017-07-17 06:21:', fuzzy=True)
```
> Fix incorrect index check, add test that fails pre-PR

- dateutil/parser.py
I don't really expect/intend this to be merged, just want to show the places that I think make for easy refactoring wins.  These will be easiest to view commit-by-commit.
The heuristic for refactoring candidates was
- Can this be made a function without passing `res` or `ymd`?
- Is it obvious what this function would be named?"
[_build_tzinfo](https://github.com/jbrockmendel/dateutil/commit/ad1bff2157c5b4f12e9e3d0dfcdf0d08bb350f2a) and [_ampm_validity](https://github.com/jbrockmendel/dateutil/commit/9c107b9325a9438ae8cff4c8ca268ca915a9f287) just cut/paste a chunk of code from a method into a function.
[_adjust_ampm](https://github.com/jbrockmendel/dateutil/commit/ee75ff0a50e9fd73fc05941799f5af5464517558) and [_parse_min_sec](https://github.com/jbrockmendel/dateutil/commit/54deb3325d3aa28bf …
> Less of a PR than an exposition/discussion

- dateutil/parser.py
One part of the cleanup mentioned in PR #419. I implemented the `_recombine_skipped_tokens` function as indicated here (`extend`), using a token queue (`queue`) and compared that to @jbrockmendel's version with a `set`.  Here is the code for the `queue` version:
```python
def _recombine_skipped_queue(tokens, skipped_idxs):
"""
>>> tokens = ["foo", " ", "bar", " ", "19June2000", "baz"]
>>> skipped_idxs = set([0, 1, 2, 5])
>>> _recombine_skipped(tokens, skipped_idxs)
["foo bar", "baz"]
"""
skipped_tokens = []
idx_queue = []
for idx in skipped_idxs:
if idx_queue and idx - 1 == [-1]:
if len(idx_queue) and idx - 1 != idx_queue[-1]:
skipped_tokens.append(''.join(map(tokens.__getitem__, idx_queue)))
idx_queue = []
idx_queue.append(idx)
if idx_queue: …
```
> Tweak to parser skipped_idx + PEP8 cleanup

- dateutil/test/test_utils.py
- dateutil/utils.py
Per the discussion in #431 and #432 this is the (fixed) `within_delta` from justanr/datestuff. I ended up finding a bug that a negative timedelta would return False, so using `abs` on it before doing the negative/positive comparison fixes that.
> Implement utils.within_delta

- dateutil/test/test_tz.py
- dateutil/tz/tz.py
Per [these comments on #429](https://github.com/dateutil/dateutil/pull/429#issuecomment-320507666) according to [RFC 5544 3.6.5](https://tools.ietf.org/html/rfc5545#section-3.6.5), `VTIMEZONE` only supports the optional `VALUE=DATE-TIME` parameter,  so anything else is filtered out.
> Improve RFC5545 support in tzical, tweak tests.

- .travis.yml
- dateutil/tz/_common.py
- tox.ini
Turns out that pypy3's implementation of `datetime.replace` doesn't return `self.__class__`, it always returns `datetime`. This fixes that issue and makes pypy3 a required pass.
> Improve fold backport compatibility.

- dateutil/rrule.py
- dateutil/test/test_rrule.py
Fixes #86 ; courtesy to @jarondl for the initial patch
> Added 'RRULE:' in rrule.__str__ to be RFC compliant

- dateutil/parser.py
Doc says UTC offset is in minutes but the example snippet uses seconds. Actually trying it would seem to confirm seconds is correct.
The example snippet also shows BRST to be -3 hrs, https://www.timeanddate.com/time/zones/brst shows it to be -2 hours so i changed it to be -7200
> updated parse() docstring to reflect tzinfos integer offset units and example 

- setup.py
Fixes #464.
I'm not 100% on what the right thing to put in this `license` line here. Most people seem to use "BSD" to refer to either the 2-, 3- or 4- clause versions and there doesn't seem to be a single canonical name for the 3-clause license, [according to Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22BSD_License_2.0.22.2C_.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29). I picked the most official-sounding one that seemed unambiguous, but maybe "BSD 3-clause" or "BSD (3-clause)" would be best?
> Change license information in setup.py

- dateutil/parser.py
As suggested in my earlier review, this moves all the parsing-related functions back into the `parser` object.
> Refactor new parser functions to keep them in the parser object

- .travis.yml
- dateutil/test/test_utils.py
- dateutil/utils.py
- setup.py
This seems like a convenience function that would be useful, particularly for passing in to `parser.parse` as `default`.
> Add dateutil.utils.today

- dateutil/test/test_utils.py
- dateutil/utils.py
- docs/index.rst
- docs/utils.rst
As a partial and possibly more general fix to #94, this adds a `tzinfo` to any `datetime` that doesn't have one, and otherwise leaves it alone.
> Add default tzinfo

- appveyor.yml
It seems that Appveyor's Python versions come with pip installed already. Since we were having SSL/TLS problems causing failing builds, this should fix that.
> Remove unnecessary pip download from Appveyor

- dateutil/zoneinfo/__init__.py
Specifically, this was confusing to mypy.
The new code is slightly easier to understand if you don't know what's going
on, IMO, otherwise I wouldn't necessarily change valid upstream code to appease
a typechecker.
Specifically, before this change:
```
$ mypy dateutil/zoneinfo/__init__.py | grep zoneinfo
dateutil/zoneinfo/__init__.py:18: error: Name 'tzfile' already defined (possibly by an import)
dateutil/zoneinfo/__init__.py:18: error: Cycle in inheritance hierarchy
```
That Cycle inheritance one is bad enough to cause mypy to give an error even
with `--follow-imports=silent`, which might be a bug in mypy, but, like I said,
I think the new code is more obvious to humans.
> Make zoneinfo tzfile superclass less confusing

- dateutil/__init__.py
- dateutil/test/test_import_star.py
Even if using import * is discouraged in general and considered a bad practice, it is considered by convention to define the public API of a module. That combined with some users asking for it lead to this commit.
Closes #406
> Define __all__ in the top level package

- dateutil/parser/__init__.py
- dateutil/parser/_parser.py
- dateutil/test/test_imports.py
- dateutil/test/test_internals.py
- dateutil/tz/tz.py
Porting the change from the `isoparser` branch into its own branch. Since `isoparser` no longer wants to build the tests and I'm in for a big complicated rebase, I might as well backport this change so that new changes don't continue causing problems.
@jbrockmendel
> Move parser

- dateutil/test/_common.py
- dateutil/test/test_imports.py
- dateutil/test/test_tz.py
- dateutil/tz/__init__.py
- dateutil/tz/tz.py
Python assumes that `tzinfo` objects representing the same zone are effectively singletons, which is why intra- vs inter-zone semantics apply based on `dt1.tzinfo is dt2.tzinfo`, not `dt1.tzinfo == dt2.tzinfo`.
`tzutc()` is the simplest case, since it only ever represents one zone. I've also added a convenience constant to the top level `tz/__init__.py`, so people can just use it as a constant.
Eventually the other classes will store their representations in caches (though this is more complicated and has more implications for the API long term).
> Return a singleton from tzutc()

- dateutil/test/test_tz.py
- dateutil/tz/_factories.py
- dateutil/tz/tz.py
This is more or less the strategy I've come up with for handling singleton zones. It's fairly efficient from my profiling with `tzoffset`.
The next obvious candidate is `tzlocal()`, but I think that one is slightly trickier to handle, I'll make an issue for discussion.
> Add time zone factories (tzutc, tzoffset)

- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
Fixes #293.
@jbrockmendel Let me know if I missed something here, but it seems like all this checking for missed year tokens is unnecessary since `_ymd` is remembering which one is the year in the first place. This also allows us to drop the time string from `_ymd` (it didn't belong there anyway).
> Use the self.ystridx already found for unambiguous year < 99 dates

- README.rst
Supplants #512.
This adds a gitter for the project, in case anyone wants that.
Also, the pypi downloads badge stopped working some time ago, so we can remove it until something better comes along.
> Add gitter badge, remove defunct pypi badge

- dateutil/parser/__init__.py
- dateutil/test/test_internals.py
Per my comments in pandas-dev/pandas#18141, I think that it is not particularly expensive to preserve some of the private interface, with an explicit deprecation warning.
The main question I have here is whether we should use `DeprecationWarning`, which is not visible by default in Python 2.7+, or if we should use something more visible, like our own custom warning class that *is* visible, or possibly make some sort of context manager that temporarily enables `DeprecationWarning`.
Kinda unfortunate that `DeprecationWarning` was disabled by default, since that encourages libraries to do shit like what I just described, but it is what it is.
> Deprecate private interfaces

- appveyor.yml
Short-to-medium term fix for #520,  until codecov/support#402 is solved in a release to the python `codecov` client.
> Pin codecov and py dependencies on Appveyor.

- dateutil/parser/_parser.py
The giant try/except that catches ValueError, IndexError, AssertionError needs to go away.  This changes two assertion into checks that raise ValueError, stops catching AssertionError.
> change assertions to ValueError, stop catching AssertionError

- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
Fixes #417 in favor of #418 (with rebase and adding limited support for Python 2).
> Bytesarray parse

- requirements-dev.txt
Trying to fix whatever new issues have been created by whatever's happening with py's support for Python 3.3 (see #526).
> Pin pytest dependency on 3.3

- CONTRIBUTING.md
- README.rst
This is an initial version of `CONTRIBUTING.md`.  It adds the stipulation that all new contributions will be dual-licensed under Apache 2.0 and BSD 3-clause license so it's more explicit what the licenses are.
> Add CONTRIBUTING.md

- setup.py
This will print a message explaining how to run the test suites when attempting to run `python setup.py test`. Resolves #544.
> Print warning when running 'setup.py test'

- AUTHORS.md
- setup.py
This closes #537 
Adds python_require to setup() in setup.py. Only works for users installing with pip 9 or above. Will warn if setuptools version is <=24.3.
Also help from Stefan Bonchev
> Adds python_require

- AUTHORS.md
- dateutil/parser/__init__.py
- dateutil/parser/_parser.py
- docs/parser.rst
Note as implemented, this puts the docs for `isoparse` at the top, which feels a bit odd. Let me know what you think.
> Fix up isoparse documentation.

- dateutil/test/test_isoparser.py
- setup.cfg
This makes an `xpass` a failure unless otherwise specified.
Also we had one xpass on `pypy` that *should have* been an `xpass` on Python 2.7, so I fixed that and made it conditional.
> Make xfails strict

- .travis.yml
- README.rst
- dateutil/parser/_parser.py
- dateutil/parser/isoparser.py
- dateutil/relativedelta.py
- dateutil/tz/tz.py
- dateutil/zoneinfo/__init__.py
- dateutil/zoneinfo/rebuild.py
- docs/conf.py
- docs/examples.rst
- docs/relativedelta.rst
- docs/zoneinfo.rst
- tox.ini
and trigger automatically at CI (also check links in documentation to avoid having dangling pointers to the internet)
> add document generation to tox

- AUTHORS.md
Adding a new flag so that it will be obvious whose contributions have been released under the new license.
> Add D flag for dual-license-only contributors.

- dateutil/parser/_parser.py
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
This pr fixes #259. As discussed with @pganssle in the dateutil sprint in London, the fix consist in modifiying `dateutil.parser._parser._tzparser.parse` to check if all tokens generated from the input string have been consumed (except separators that are assumed to be "," and ":" as specified [here](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html)). To have some control (and help future debugging) on the tokens that are not used, a mark of used_tokens is used internally to keep track of this. To avoid making the parser raise and therefore modifiying the current behaviour, a new slotted field was added to `dateutil.parser._parser._tzparser._result` that indicates if all tokens have been consumed or not. This is used in `dateutil.tz.tz.tzstr` to raise accordingly in the …
> Make tz.tzstr fail if an invalid GNU tz string is provided

- dateutil/test/test_tz.py
- dateutil/tz/tz.py
Should fix the `tzlocal() == tzutc()` question in #64.
> Expand equality for tzlocal

- AUTHORS.md
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
I just found an edge case (I believe) that was not handled properly. It seems like the slice on the `TZ` environment variable value was incorrect, using `name[:-1]` instead of `name[1:]`.
I would end up with the following:
```
(Pdb++) name
':/etc/localtim'
```
... instead of:
`/etc/localtime`
The default timezone value can be `TZ=:/etc/localtime`. It may vary, but usually starts with `:`.
Documentation: https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
> If the TZ environment variable does not have a value, the operation chooses a time zone by default. In the GNU C Library, the default time zone is like the specification ‘TZ=:/etc/localtime’ (or ‘TZ=:/usr/local/etc/localtime’, depending on how the GNU C Library was configured; see Installation). Other C libraries use …
> Fixes handling of the GNU C Library default timezone value

- dateutil/parser/_parser.py
- dateutil/test/test_internals.py
- dateutil/test/test_tz.py
- dateutil/tz/__init__.py
- dateutil/tz/tz.py
- docs/examples.rst
Fixes #595.
This is a release blocker, so we should get this out ASAP.
CC: @pablogsal
> Deprecate tz format

- dateutil/parser/__init__.py
- dateutil/parser/_parser.py
- dateutil/test/test_imports.py
Preparing for the 2.7.0 release, I don't want to have a half-done implementation of #335. For now we'll go back to all `ValueError` and then implement the new subclasses strategy in one fell swoop.
> Only raise ValueError in parser for now

- dateutil/easter.py
This should unbreak the (possibly overzealous) CI, which is treating permanent redirects as errors.
That said, it's a good idea to link to HTTPS when possible.
> Update tondering.dk link to use HTTPS

- dateutil/parser/isoparser.py
- dateutil/test/test_isoparser.py
My goal for the isoparser in the future is to allow more customization of the parse to allow the user to be more or less strict than the ISO 8601 standard, but I think it's time to get the 2.7.0 release out the door, so I've tweaked the documentation to indicate that the strictness of the default `isoparse` is not something to rely on (until the strictness can be specified).
Additionally, in a nod to pragmatism (since a huge number of people use ISO 8601 with a space separator rather than a `T` separator), I've relaxed the strictness of the parser to accept *any* single ASCII character by default, rather than just `T`. This brings the behavior more in line with the forthcoming [`datetime.fromisoformat`](https://docs.python.org/3.7/library/datetime.html#datetime.datetime.fromisoformat) …
> isoparser strictness clarification and relaxation

- dateutil/rrule.py
- dateutil/test/test_rrule.py
This is a fixup PR for #619, see the discussion there for more details. It fixes #614. 
I realized that `tzinfos` in the parser and `tzid` want slightly different things in this scenario. Considering that the RFC is actually a lot stricter than `dateutil.parser.parse` about the format of the dates, in a future version I will try to deprecate the looser parser, possibly in favor of `dateutil.parser.isoparse`.
Either way I'll probably deprecate the use of `tzinfos`, since the RFC dictates that the time zone should go in the `TZID` parameter, not the datetime itself.
> Support for TZID= in rrulestr

- dateutil/test/test_tz.py
- dateutil/tz/_factories.py
- dateutil/tz/tz.py
For the upcoming 2.7.0 release, I think it's important for at least `tz.gettz` to return the same zone for the same inputs unless otherwise specified.
This PR makes `tzstr` a singleton, adds caching to `tz.gettz` and adds the `.instance` alternate constructor for `tzoffset` and `tzstr`.
I did not bother with a `.instance` alternate constructor for `tzutc`, because the semantics of `tzutc` are not affected by inter- and intra-zone comparisons (technically true of `tzoffset` as well, too).
> More caching and singletons in tz

- dateutil/parser/__init__.py
- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
Current incorrect behavior:
```
>>> parser.parse('2017-12-05 08:38 EST')
datetime.datetime(2017, 12, 5, 8, 38)
```
This PR raises instead of silently dropping this timezone information.
This surfaces two test failures that look like false-positives slipped through and got assigned to res.tzname.  Thats the "WIP" part of the PR.
```
___________________________________________ ParserTest.testFuzzyIgnoreAMPM ___________________________________________
[...]
timestr = 'Jan 29, 1945 14:45 AM I going to see you there?'
res = _result(year=1945, month=1, day=29, hour=14, minute=45, tzname=u'I')
___________________________________________ ParserTest.testRandomFormat26 ____________________________________________
[...]
timestr = '5:50 A.M. on June 13, 1990'
_result(year=1990, month=6, day=13, …
```
> Warn on unidentified tz

- setup.py
Missed this in the switchover from BSD to Apache.
> Fix license trove classifier

- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
Fixes #632.
This adds both function call overhead and exception catching overhead to the function. Based on running `%timeit` on a few strings, the cost is on the order of a few microseconds out of 60-100 microseconds. If we can come up with a version that doesn't have to re-raise, that might be preferable.
Also, we could theoretically add whatever errors `Decimal` is raising into the huge try-except loop and handle it that way, but the documentation doesn't seem to clearly enumerate an exception hierarchy for `decimal.Decimal`, so I'm not confident that we could catch the "root" exception easily.
> Catch non-ValueError exceptions in decimal

- dateutil/rrule.py
- dateutil/test/test_rrule.py
related: https://github.com/dateutil/dateutil/issues/620
related: https://github.com/dateutil/dateutil/issues/633
> require UTC for UNTIL when DTSTART is timezone-aware

- CONTRIBUTING.md
- changelog.d/template.rst
- pyproject.toml
Fixes #592.
At the moment town crier seems like the best option out there for changelog management. It does pretty much what I want, except I don't think the ticket-based workflow definitely works for this project.
Ideally we'd have something like town crier that allows additional metadata to be specified in the `.rst` so that I can add "reporter", "pr", "issue" and "patch submitter". Also, it would be nice to be able to specify an "issue template" so users could do something like `towncrier entry` and it would maybe ask a few questions then generate a basic template.
Still, this is waaaay better than what I've been doing, and seem better than anything else out there.
> Add towncrier for changelog management

- changelog.d/0633.bugfix.rst
- changelog.d/0634.bugfix.rst
- changelog.d/0643.data.rst
- changelog.d/0644.misc.rst
Backfill of the town crier log now that #645 is merged.
> Add changelog entries for changes since 2.7.0

- changelog.d/648.misc
- setup.py
This should make the [PyPI page](https://pypi.org/project/python-dateutil/) a lot less sparse.
> Add README.rst as long_description

- NEWS
- setup.py
This PR prepares the 2.7.1 release.
This also makes a fix to #648, because the `README.rst` makes use of an unsupported feature on the PyPI renderer.
The release notes are below:
Version 2.7.1 (2018-03-24)
===========================
Data updates
------------
- Updated tzdata version to 2018d.
Bugfixes
--------
- Fixed issue where parser.parse would occasionally raise
decimal.Decimal-specific error types rather than ValueError. Reported by
@amureki (gh issue #632). Fixed by @pganssle (gh pr #636).
- Improve error message when rrule's dtstart and until are not both naive or
both aware. Reported and fixed by @ryanpetrello (gh issue #633, gh pr #634)
Misc
----
- GH #644, GH #648
> Release 2.7.1

- changelog.d/0633.bugfix.rst
- changelog.d/0634.bugfix.rst
- changelog.d/0643.data.rst
- changelog.d/0644.misc.rst
- changelog.d/648.misc
There was some bug and towncrier did not remove these, and I forgot to do it manually.
> Remove old news fragments

- AUTHORS.md
- changelog.d/651.misc.rst
- setup.py
With the current setup script, the build fails (I only tested with Python 3.4) in a non-UTF-8 environment
e.g. `LC_ALL=C pip3 install .` fails prior to this patch
This fails because `open` uses the system encoding by default and the `README.rst` file contains non-ascii characters.
This PR enforces the opening of `README.rst` with the UTF-8 encoding. This fixes the build when running the setup script on non-UTF-8 setups.
> Open README.rst with utf-8 encoding

- README.rst
- changelog.d/655.misc
Warehouse seems definitely mature enough that we should be linking to it rather than the old PyPI.
Correct me if I'm wrong @ewdurbin, but I think it's time for this.
> Update readme links to pypi.org

- NEWS
- changelog.d/651.misc.rst
- changelog.d/655.misc
- pyproject.toml
Cutting a new release to include #651, which I suspect might start giving people trouble at install time soon.
> Release 2.7.2

- AUTHORS.md
- changelog.d/0679.bugfix.rst
- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
This fixes an edge case for decimal parsing.
When we are receiving `Nan` or infinite value in `_to_decimal` (which theoretically should not be possible), we are raising a `ValueError`, instead of continuing with it.
Thank you @pganssle for the suggestion, please, check if this solution fits well.
> Catch infinite decimal values in `_is_decimal` (fix #662)

- AUTHORS.md
- changelog.d/672.bugfix.rst
- dateutil/test/test_tz.py
- dateutil/tz/_factories.py
- dateutil/tz/tz.py
> Updates Tz Singletons and Caches with `WeakValueDictionary`s

- .gitignore
- dateutil/parser/isoparser.py
- dateutil/utils.py
Neither isoparse nor the utils module were documented as being added in 2.7.0 before this.
Closes #625
I also piggy-backed adding `.mypy_cache` into the gitignore on this PR.
> Update version added documentation

- changelog.d/688.misc.rst
- dateutil/test/property/test_isoparse_prop.py
Tests the property that `dateutil.parser.parse` will support inversion of `dt.isoformat()` in the somewhat limiting case that `sep` is an ASCII character.
> Add hypothesis tests for isoparse

- AUTHORS.md
- changelog.d/681.bugfix.rst
- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
Return `None` if the user would like to ignore the timezone in the date parse.
Fix typo in warning in `_build_tzaware` 
This is a WIP on #661.
Closes #661
> 661 tzinfos could be None in call to parse

- README.rst
- docs/conf.py
Rather than removing the pgp.mit.edu link, I've kept it as the primary link, but added a mirror to sks-keyservers.net. To avoid the intermittent failure problems, I've increased the number of retries for `linkcheck` and started ignoring the now-flaky pgp.mit.edu as part of the linkcheck.
The question of whether these linkchecks should be required for every PR review is still open, but I'll address that separately later if it continues to cause problems.
Fixes #694
> Add linkcheck options

- AUTHORS.md
- changelog.d/695.doc.rst
- dateutil/rrule.py
Changed order in the rrule docstring to match with order of the keywords.
Closes #686
> change the order of cache and byeaster in rrule docstring

- AUTHORS.md
- changelog.d/699.misc.rst
- dateutil/test/test_tz.py
Added unittest to check if tz's objects "_filename" attribute is equal to the "name" object of an input fileobject.
Closes 
N/a - related to *Get coverage to 100%* (#521)
> Add test for repr of named fileobject in tzfile

- NEWS
- changelog.d/692.doc.rst
- changelog.d/707.doc.rst
- docs/changelog.rst
- docs/conf.py
- docs/index.rst
- docs/requirements-docs.txt
- tox.ini
Adds the changelog to the documentation.
While I was in there I also changed the default documentation build to use the sphinx_rtd_theme, and some configuration changes to go with that.
Closes #692
> Add changelog to documentation

- changelog.d/687.bugfix.rst
- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
Replaces #698.
At the moment `_ymd.resolve_ymd` can ignore `ystridx` and `dstridx` in some corner cases. This PR has `resolve_ymd` check if enough of `[ystridx, mstridx, dstridx]` have been specified to uniquely pin down (year, month, day), and if so, use those instead of other heuristics.
Edits resolve_ymd  to prevent deleting an element in-place, which makes step-through debugging more difficult.
Closes #687
> Fix for B.Y.d format corner case #687

- changelog.d/714.doc.rst
- dateutil/tz/__init__.py
- dateutil/tz/tz.py
- docs/tz.rst
This is a light restructuring of the tz documentation because the automodule-generated stuff was not great to read.
The downside of using all these explicit directives is that if we forget to add something to `tz.rst` it won't get added to the documentation, but given how much stuff we've forgotten to document *anyway* we should probably be improving discipline on that anyway. At least this way we don't have to wait until the build is done to figure out if something is missing.
> Restructure tz docs

- AUTHORS.md
- changelog.d/672.bugfix.rst
- dateutil/test/test_tz.py
- dateutil/tz/_factories.py
- dateutil/tz/tz.py
This reverts #672 on the 2.7.x branch, since it's actually a somewhat big change, performance-wise, for a patch release.
> Revert weakref

- changelog.d/721.bugfix.rst
- dateutil/parser/isoparser.py
- dateutil/test/test_isoparser.py
ISO 8601 allows for (and actually prefers, in the :2004 standard) the use of a comma as the decimal separator. This PR adds support to `isoparse`
> Comma separator for ISO 8601 parser

- .travis.yml
- changelog.d/723.misc.rst
- setup.py
New version of #722 because Travis was acting up.
Fixes #724
> Fix Python 3.3 tests, make setup.py PEP 8 compliant

- AUTHORS.md
- changelog.d/726.misc.rst
- dateutil/test/test_easter.py
@pganssle suggested that it would be good to migrate the tests to parameterized pytests.
I've dropped the for easter_date in to loop over cases. The problem with that is once an assertion fails, none of the following tests in the loop will be ran. Now, even if the first test case for each of the easter tests cases fails the following will still be ran. Also, since the refactor was for all of the test cases in the file I applied a PEP8 format to the file.
Closes
> conversion of test_easter.py to use pytest

- changelog.d/727.misc.rst
- dateutil/test/test_parser.py
@pganssle suggested that it would be good to migrate the tests to parameterized pytests.
This is a possible partial conversion.
I've tried to keep the grouping and meaning of test cases the same.
I've converted the old test function signatures to assertion messages. Where appropriate, I've integrated the comments from the test cases into the error messages as well. I've noticed that a large number of the test cases weretestSomeThing1, testSomeThing2, testSomeThing3,... where the trailing number has appeared to be indexing the i'th test case I have dropped it.
Closes
> parametrize part of parser test cases with pytest

- AUTHORS.md
- changelog.d/750.misc.txt
Relicence commits I made prior to the move by the project to Apache 2.0 I declare that I hold the original copyright, and that they may be licensed under Apache 2.0 terms.
> Relicence my previous commits under Apache 2.0

- changelog.d/582.bug.rst
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
As described in python bug tracker (https://bugs.python.org/issue5288), datetime now allows offsets that are not an integer number of minutes. Dateutil now accounts for this when running in newer versions of python
- Add "Africa/Monrovia" to test_resolve_imaginary test for python 3.6 or newer
- Test that partial minutes is supported in python 3.6 or newer for tz.tzfile and datetime.utcoffset
- Enable partial minutes in both tz.tzoffset and tz.tzfile
- For now, don't warn user when rounding to nearest minute for python pre-3.6
Closes #582
> Closes #582: Allow partial minutes for python 3.6 or newer

- changelog.d/772.misc.rst
- dateutil/test/test_isoparser.py
Add test for invalid separator in ISO parser.
> Add test for invalid separator in isoparser

- changelog.d/773.bugfix.rst
- changelog.d/773.misc.rst
- dateutil/parser/isoparser.py
- dateutil/test/test_isoparser.py
I discovered this when writing tests to hit the last uncovered line in isoparser.py, `parse_isotime` was actually parsing all time strings twice - first it would parse and adjust 24 -> 0, then it would parse again and pass the unmodified string directly to `datetime.time`.
This adds fixes the behavior and brings the test coverage to 100%.
> Fix isotime behavior for strings with hour == 24

- AUTHORS.md
- changelog.d/753.doc.rst
- docs/examples.rst
Added a doctest example to demonstrate how to override parserinfo.  XM does not appear to be common with 12 hour date format so we should probably not include in default parserinfo.
Closes #426
> #426 parse xm times

- AUTHORS.md
- CONTRIBUTING.md
- changelog.d/757.doc.rst
Amends the documentation for creating changelog entries to include where to put the files, so that noobs like me know exactly what to do!
No issue for this change.
- N/A Changes have tests
> Changelog documentation

- changelog.d/780.misc.rst
- dateutil/test/test_import_star.py
- setup.cfg
This makes the tests stricter by enforcing that the test suite raises no warnings accidentally, including deprecation warnings.
As part of adding this, I realized that the test suite was using `self.assertEquals`, so I converted it first to the non-deprecated version and then moved `test_import_star` over to a pytest-style test.
> Warnings as errors

- AUTHORS.md
Many people either did not add themselves to the list or did not use the **D** flag to indicate that they have only contributed during the time of dual-licenses. This updates everyone who was dual-license only.
@tacaswell @jonemo @kootenpv @labrys @ryanss Can I switch y'all over to **R** (i.e. your old commits are relicensed under both BSD and Apache 2.0 instead of just BSD - both are compatible permissive licenses)?
> Add dual license flag for recent contributors

- AUTHORS.md
- changelog.d/787.bugfix.rst
- dateutil/parser/isoparser.py
- dateutil/test/test_isoparser.py
RFC 3339 does not specify a limit to the number of fractional digits
that can be provided. In the wild, languages like Go will provide up
to 9 digits by default.
Since the standard library's `datetime` only supports precision down
to microseconds, any extra digits in the fractional component are
truncated.
Closes #786
> Accept more than 6 fractional digits in `isoparse`

- changelog.d/791.misc.rst
- dateutil/tz/tz.py
The _ContextWrapper class was added before nullcontext was added
to the standard library. When available, we should prefer to use
nullcontext.
> Use Python3.7's nullcontext if available

- .travis.yml
- changelog.d/799.misc.rst
Not sure why but `setuptools` seems to have started breaking on Python 3.3
> Pin setuptools version on Python 3.3

- AUTHORS.md
- dateutil/test/test_parser.py
Add test cases that already pass. I'm working on a reimplementation of the parser in Rust, and copied all the test cases from dateutil; found out tonight there was a bug because I wasn't handling "GMT+03" correctly, and so wanted to add these as part of the coverage.
- [✓] Changes have tests
- [✓] Authors have been added to [AUTHORS.md](https://github.com/dateutil/dateutil/blob/master/AUTHORS.md)
- [N/A] News fragment added in changelog.d. See [CONTRIBUTING.md](https://github.com/dateutil/dateutil/blob/master/CONTRIBUTING.md#changelog) for details
> Add test cases for positive offsets

- changelog.d/810.bugfix.rst
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
This is a test and fix for the bug first reported [in this StackOverflow question](https://stackoverflow.com/q/52136980/467366), and migrated to GH in issue #812.
When cleaning that up, I discovered a cleaner way to handle the issue of Portugal's base offset shift without a corresponding total offset shift, obviating the need for a second traversal of the transition list.
Fixes #812.
> Fix bug with Samoan offset change, refactor base offset change handling

- changelog.d/811.bugfix.rst
- dateutil/tz/_common.py
This improves the ability to inspect wrapped tzname methods in Python 2
and removes an unnecessary function call (to the nested function) in
Python 3. From my measurements, this is about twice as fast in Python 3
and approximately the same speed in Python 2.
- Changes have tests (N/A)
> Improve tzname_in_python2 decorator

- changelog.d/813.misc.rst
- dateutil/test/test_parser.py
- dateutil/test/test_tz.py
More forward compatible by slightly reducing unnecessary use of the six library.
> Always use io.BytesIO/StringIO over six; on all supported Pythons

- docs/requirements-docs.txt
Sphinx made some sort of type annotation related change that is throwing a warning for `rrule.rrulestr` which is a callable object defined in a closure rather than a Python function object. Until they fix this bug, we'll pin to the previous version of Sphinx.
See https://github.com/sphinx-doc/sphinx/pull/5345 for where this seems to be breaking.
> Pin sphinx to <1.8.0 for docs build

- changelog.d/814.bugfix.rst
- setup.py
The error message was printed, but the process exited with 0.
That is extremely error prone in automated environments.
Also, print the error message to standard error.
This is **completely untested** as I'm doing the change from the web interface.
I will eventually get to this from a machine where I can clone and rebase and stuff.
> setup.py test doesn't work, so exit with 1

- docs/requirements-docs.txt
The callable function typing issue should be fixed in sphinx commit bbb4593bfaa65611b6bd600c5, so the next release after 1.8.0 should contain the fix.
Fixed in GH sphinx-doc/sphinx#5431
https://github.com/sphinx-doc/sphinx/commit/bbb4593bfaa65611b6bd600c5e37c4c54af87f1a
Probably best to wait until a new version of Sphinx is released to merge this rather than just having to revert it if the new version still doesn't work.
> Change sphinx pin to != 1.8.0

- changelog.d/817.bugfix.rst
- dateutil/parser/_parser.py
- dateutil/test/test_isoparser.py
The `bytes` type is available on all supported Pythons. Can remove workaround and make the code more forward compatible with Python 3.
> Remove unnecessary binary_type compatibility shim

- changelog.d/767.misc.rst
- dateutil/test/test_parser.py
For the sake of inventorying existing parser tests, this separates out tests that are specifically about supporting different types of inputs.
> Separate out input_format tests

- changelog.d/822.bugfix.rst
- dateutil/parser/_parser.py
- dateutil/parser/isoparser.py
- dateutil/test/test_isoparser.py
- dateutil/test/test_parser.py
Accepting 'z' as valid UTC in isoparser
Closes #820
> BUG: Closes #820 Accepting 'z' as valid UTC in isoparser

- requirements-dev.txt
freezegun version 0.3.11 has the common issue of incorrect PyPI metadata
mismatched with Requires-Python:
https://github.com/spulec/freezegun/issues/268
> Pin freezegun on Python 3.3

- AUTHORS.md
- changelog.d/761.feature.rst
- dateutil/test/test_tz.py
- dateutil/tz/_factories.py
- dateutil/tz/tz.py
I prepared a benchmark script and here are the results without the patch:
Benchmark:
https://gist.github.com/gokcennurlu/2b4e9d82e255c73e920c00ca5d26dcec
Results without patch:
```bash
3951.2012898921967 μs (tz.gettz() calls without storing values)
12.26398441940546 μs (tz.gettz() calls with storing values)
58.90091247856617 μs (tz.tzoffset() calls without storing values)
9.584207087755203 μs (tz.tzoffset() calls with storing values)
284.80793107300997 μs (tz.tzstr() calls without storing values)
7.534163072705269 μs (tz.tzstr() calls with storing values)
```
Results without patch:
```bash
27.99563854932785 μs (tz.gettz() calls without storing values)
28.635493479669094 μs (tz.gettz() calls with storing values)
22.882843017578125 μs (tz.tzoffset() calls without storing values) …
```
> Add LRU caching to tzoffset, tzstr and gettz

- changelog.d/000.data.rst
- zonefile_metadata.json
Updates tzdata to the latest version - 2018f.
> Update tzdata to 2018f

- pyproject.toml
The CI is broken once again on Python 3.3, trying to fix this.
I believe this is a problem with `python_requires` when installing `setuptools` on Python 3.3.
This does not bode well for dropping support for python 2, though this may be just the fact that it's using a fairly old version of `pip`.
> Update pyproject.toml for version 3.3

- changelog.d/836.misc.rst
- dateutil/test/conftest.py
- tox.ini
This automatically attaches the `no_cover` marker to anything marked `xfail` *if* the `xfail` condition is met. This allows us to do the test coverage in one run instead of two.
> Skip coverage on xfailed tests

- changelog.d/857.misc.rst
- dateutil/test/conftest.py
I simply added a default value to the getattr call that is used only on python3.3 which should hopefully not be used anymore but in case it happens and the getattr fails (which it shouldn't) then the marker is skipped.
Closes #857
> Fixed get_marker API change introduced by pytest version >= 4.0

- changelog.d/861.bugfix.rst
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
On Windows and Python 2.7, calling `tzwin` with a non-ascii name will raise a `UnicodeEncodeError` instead of `WindowsError`, as it does on other platforms and versions.
Fixes GH #802.
> Catch UnicodeEncodeError for Windows in tz.gettz

- MANIFEST.in
- changelog.d/863.bugfix.rst
- pyproject.toml
This explicitly specifies `dateutil`'s backend and ensures that `pyproject.toml` is in the sdist.
> Add build backend to pyproject.toml

- NEWS
Somehow a bunch of old changelog stubs from 2.7.3 got included in the 2.8.0 release notes. This updates the release notes accordingly. We'll have to make a `post` release to get the documentation updated.
> Fix changelog

- azure-pipelines.yml
- ci_tools/run_tz_master_env.sh
- tox.ini
Hi! I'm a product manager on Azure Pipelines. We've been helping a lot of Python projects move over to Azure Pipelines for continuous integration. There are a few key benefits we offer:
- Generous free allowance for open source projects - 10 jobs in parallel, plenty of minutes
- All 3 major platforms - Linux, macOS, and Windows - hosted in Azure
- Great test analytics giving you insight into pass/fail rates on tests over time
I'm hoping you'll give us a try! The easiest way to get started is to let azure-pipelines.yml land in master, then install the [Azure Pipelines app](https://github.com/marketplace/azure-pipelines). If that's a bit too much, you can install the app, let it put a dummy azure-pipelines.yml in a branch, then go in and try out the build against this PR's branch. Even even …
> add Azure Pipelines

- AUTHORS.md
- changelog.d/879.misc.rst
- dateutil/test/test_isoparser.py
1. added #pragma: no cover to the if and def lines not tested on Python 2 and 3
2. Change the time_val to tstr in if isinstance to hit in test_isoparser
Closes  #776
> Improve coverage in test_isoparser

- dateutil/test/test_parser.py
Most of the parser tests are written with the older unittest structure.  Now that we're using pytest, some of that can be cleaned up.
The only substantive change is using a classmethod `setup_class` instead of a regular method `setUp`, so it only gets called once instead of for each test.  Small-n it looks like this saves 20-30% of the runtime for that file (which is only 3-5 seconds, so really not a big deal).
There are a lot of `self.assertEqual` statements so getting them all will take a few passes.
> use setup_class instead of setUp

- changelog.d/735.misc.rst
- changelog.d/882.misc.rst
- dateutil/parser/_parser.py
The methods within `parser` are a bit of a jumble.  This separates out two sections for methods that a) act on individual tokens and b) are for creating the datetime output after the string is fully parsed.
No hurry on this if it would cause rebasing conflicts elsewhere.
Methods are unchanged, with the exception of a long line in a comment in to_decimal that is wrapped.
> REF: collect parser methods by function

- changelog.d/890.misc.rst
- dateutil/test/test_parser.py
Add a check so that duplicates don't sneak back in.
Rename TestInputFormats to the more accurate TestInputTypes.
A couple more test-cleanup PRs coming up (one with an actual bugfix), trying to keep them small and orthogonal.
> Remove duplicate tests

- changelog.d/894.misc.rst
- dateutil/test/test_parser.py
Most of these tests have uninformative names and no comments, so nothing is lost by parametrizing them.
This shouldn't create merge conflicts with #891 and #892.  I'll wait on these three before doing the next round.
Will add a changelog momentarily
> Parametrize tests for ignore_tz, dayfirst, yearfirst

- .travis.yml
- azure-pipelines.yml
Currently the `tz` env breaks when run with tox >= 3.8.0 due to some problem with the weak caches not invalidating properly. As a short-term mitigation, we will pin the tox version until we can get to the root of the problem.
This is a short-term mitigation for #908.
> Pin tox to 3.8.0 in CI

- AUTHORS.md
- changelog.d/881.bugfix.rst
- dateutil/parser/__init__.py
- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
If multiple arguments are passed in, it raises a tuple, not one string.
xref https://github.com/pandas-dev/pandas/pull/25430#discussion_r259614777
> Use custom ParserError class in parser exceptions

- changelog.d/910.bugfix.rst
- dateutil/parser/_parser.py
- dateutil/parser/isoparser.py
- dateutil/rrule.py
- dateutil/test/property/test_isoparse_prop.py
- dateutil/test/test_isoparser.py
- dateutil/test/test_parser.py
- dateutil/test/test_tz.py
- dateutil/test/test_utils.py
- dateutil/tz/__init__.py
- dateutil/tz/tz.py
- docs/examples.rst
- docs/tz.rst
In version 2.7.0, we added the `tz.UTC` object as a convenience accessor for the `tzutc` singleton. This PR goes updates other modules and tests that were using `tzutc()` to use `tz.UTC`, except where it doesn't make sense to do so.
> Use tz.UTC in favor of tz.tzutc() where possible.

- azure-pipelines.yml
Hi there, PM from Azure Pipelines here. We added `pypy2` and `pypy3` as Python "versions" for the `UsePythonVersion` task. That means you no longer have to special-case PyPy in your pipelines.
> Unify PyPy into normal flow

- changelog.d/915.misc.rst
- setup.cfg
The latest version of pytest has started warning on unregistered markers, which the test suite uses fairly extensively, causing the tests to fail. This explicitly registers all the markers 
used in the test suite.
In the future we can re-assess whether we want to replace these markers with something else, and also probably we'll want to start pinning all test and documentation dependencies.
> Register pytest markers

- azure-pipelines.yml
- changelog.d/916.misc.rst
Azure pipelines is failing because of coverage-related problems. Until we have it set up to upload coverage (which I think is getting native support soon, from what I'm told), we can just treat the "upload to codecov" job as an allowed failure.
> Don't upload coverage on azure

- .travis.yml
- changelog.d/934.misc.rst
- requirements-dev.txt
- requirements/3.3/constraints.txt
- requirements/3.3/requirements-dev.txt
- tox.ini
This does two things to alleviate the current (and hopefully all future) problems we're having testing Python 3.3:
1. Upgrade to the latest supported `pip` on Python 3.3, version 10.0.1, which actually *does* seem to support `python_requires`
2. Add a constraints file to all `pip` operations for Python 3.3 pinning all direct and transitive dependencies.
With all dependencies pinned, the 3.3 build should be more stable.
> Pin requirements more thoroughly on py33

- changelog.d/962.misc.rst
- requirements/3.3/constraints.txt
As I worried about, there are apparently some windows-specific dependencies in the testing stack that are not covered in the 3.3 constraints file, which is causing new failures.
> Pin colorama on Windows

- changelog.d/963.bugfix.rst
- dateutil/tz/tz.py
It turns out that the import of `contextlib.nullcontext` in Python 3.7+ was accidentally trying to import `contextmanager.nullcontext`, but this was never noticed because it simply fell back to the backport included here.
I do not know of a great way to test this that doesn't rely on implementation details, but I have manually tested it by setting a breakpoint after the import in the `try` statement and importing `dateutil.tz` manually on Python 3.7, so this version should work.
> Fix incorrect import in Python 3.7+

- changelog.d/966.misc.rst
- setup.cfg
It appears that we were relying on the "errors" filter to treat PendingDeprecationWarning as an error due to a typo in setup.cfg. This line is apparently redundant with the "error" line anyway, but it's best to have a working version of it if we're going to have it at all. I am leaving it in place to be explicit that even these "ignored by default" warnings should be errors, in case a default changes later.
> Fix typo in setup.cfg warning configuration

- changelog.d/969.misc.rst
- dateutil/test/_common.py
- dateutil/test/test_relativedelta.py
- dateutil/test/test_rrule.py
- dateutil/test/test_tz.py
This was originally added when we were still supporting `unittest`-only tests, but now that we require pytest, we can switch over to using the built-in `pytest.warns` context manager.
> Remove WarningTestMixin in favor of pytest.warns

- AUTHORS.md
- changelog.d/935.misc.rst
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
Fix error message for gettz when passed bytes
Closes #927
> Fix error message for gettz when passed bytes

- changelog.d/928.bugfix.rst
- dateutil/test/test_tz.py
test_tzlocal_offset_equal[GMT-tzoff1] fails if a system does not 
have a defined (installed) GMT timezone, for example if "Link Etc/GMT GMT"
is not defined in the zoneinfo configuration:
>           assert tz.tzlocal() == tzoff
E           AssertionError: assert tzlocal() == tzoffset(u'GMT', 0)
E             -tzlocal()
E             +tzoffset(u'GMT', 0)
An example of such a configuration is FreeBSD, who's default timezone is
UTC [1][2]. This configuration results in any "non-present" or undefined TZ
name being returned/processed as the default timezone name (in FreeBSD's
case, UTC).
Further, POSIX does not recognize [3] TZ=GMT or TZ=UTC as valid values
because they neither start with a colon nor contain a numeric offset hour
field.
Accordingly, update the GMT value for this parametrized …
> Fix test_tzlocal_offset_equal[GMT-tzoff1]

- changelog.d/973.bugfix.rst
- dateutil/tz/_factories.py
Since the strong cache uses operations in OrderedDict that are not thread-safe in Python 2, it is necessary to acquire a lock while updating the dictionary.
When Python 2 support is dropped, we can likely refactor this to avoid locking.
I have a small script that reproduces the issue on Python 2.7, but unfortunately it only reproduces the issue intermittently, and in the current implementation seems to be prone to deadlocks (possibly that is another issue with the tz code..), so it is not really an ideal unit test.
Still, I'll include it here in case anyone wants to verify that this solution works:
<details>
```python
from dateutil import tz
import threading
try:
from threading import Barrier
except ImportError:
from threading import Semaphore
class Barrier(object):
def __init__(self, n): …
```
> Lock around strong cache updates

- .travis.yml
- RELEASING
- changelog.d/971.misc.rst
- changelog.d/template.rst
- pyproject.toml
- tox.ini
The `RELEASING` document had gotten quite out of sync with the actual release procedure, so I have updated it.
I have also added new `tox` environments to handle the creation of virtual environments for some of the tasks around building and releasing.
> Updates to the release process

- NEWS
- changelog.d/735.misc.rst
- changelog.d/871.misc.rst
- changelog.d/875.misc.rst
- changelog.d/876.misc.rst
- changelog.d/879.misc.rst
- changelog.d/881.bugfix.rst
- changelog.d/882.misc.rst
- changelog.d/890.misc.rst
- changelog.d/891.bugfix.rst
- changelog.d/891.misc.rst
- changelog.d/892.misc.rst
- changelog.d/893.misc.rst
- changelog.d/894.misc.rst
- changelog.d/910.bugfix.rst
- changelog.d/915.misc.rst
- changelog.d/916.misc.rst
- changelog.d/928.bugfix.rst
- changelog.d/934.misc.rst
- changelog.d/935.misc.rst
- changelog.d/950.bugfix.rst
- changelog.d/952.misc.rst
- changelog.d/961.data.rst
- changelog.d/962.misc.rst
- changelog.d/963.bugfix.rst
- changelog.d/966.misc.rst
- changelog.d/969.misc.rst
- changelog.d/970.misc.rst
- changelog.d/971.misc.rst
- changelog.d/973.bugfix.rst
This updates the changelog for the 2.8.1 release, which includes the following changes:
Version 2.8.1 (2019-11-03)
==========================
Data updates
------------
-   Updated tzdata version to 2019c.
Bugfixes
--------
-   Fixed a race condition in the `tzoffset` and `tzstr` \"strong\"
caches on Python 2.7. Reported by \@kainjow (gh issue \#901).
-   Parsing errors will now raise `ParserError`, a subclass of
`ValueError`, which has a nicer string representation. Patch by
\@gfyoung (gh pr \#881).
-   `parser.parse` will now raise `TypeError` when `tzinfos` is passed a
type that cannot be interpreted as a time zone. Prior to this
change, it would raise an `UnboundLocalError` instead. Patch by
\@jbrockmendel (gh pr \#891).
-   Changed error message raised when when passing a `bytes` …
> Prepare 2.8.1 release

- appveyor.yml
- changelog.d/982.misc.rst
Appveyor has been failing recently because of Python 3.3. We're mainly still testing Python 3.3 as a sort of "canary" to determine when we can drop it from the `python_requires`, so I believe it's sufficient to just test on Travis.
I have also added Python 3.7 and 3.8 tests. For now we can do x86/x64 on 3.7 and 3.8 until 3.8 is the more common platform.
> Drop Python 3.3 on Appveyor

- appveyor.yml
- changelog.d/990.misc.rst
Builds have started failing on appveyor because we're using coverage 4.x to generate coverage data, but coverage 5.x to process it on Windows. This is because we're always using Python 3.6 to invoke `tox`, so the `coverage` job picks up a more recent version of `coverage` than the `py34` job.
As far as I can tell there are no lines uniquely hit by the Python 3.4-on-Windows tests, so we're not losing any coverage by not including it in the coverage uploads. I say it's not really worth trying to fix this, so I've just skipped the upload step on Python 3.4.
> Skip uploading Python 3.4 coverage on Appveyor

- AUTHORS.md
- changelog.d/987.bugfix.rst
- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
Guard against an integer value in ValueError args.  This is known to occur with IllegalMonthError.
Closes #981
> Fix TypeError in parser's error-wrapping logic

- changelog.d/991.bugfix.rst
- dateutil/parser/_parser.py
- dateutil/test/test_parser.py
This was originally dead code, because an indentation error had `__repr__` defined after the `return` statement in `__str__`. The definition of the `__repr__` is also changed to be more in line with the conception of a repr as "what you would have to evalue to get this object".
Even though this is not guaranteed behavior, this commit also adds a regression test to avoid simple errors like this in the future.
Closes #991
> Fix custom repr for ParserError

- README.rst
- changelog.d/992.doc.rst
- changelog.d/994.doc.rst
- dateutil/parser/_parser.py
- docs/parser.rst
This introduces four related changes:
1. Updates links with redirects or pointing to HTTP websites that have HTTPS versions.
2. Rearranges the parser documentation to break it down into functions/classes/exceptions.
3. Documents that `parser.parse` raises `ParserError` now.
4. Cleans up the docstrings for `ParserError` and `UnknownTimezone`.
Closes #992
> Parser (and other) documentation fixes

- AUTHORS.md
- README.rst
- changelog.d/1017.misc.rst
Build has been failing for a month due to the pgp mirror link being broken (502 Bad Gateway). The site seems defunct, since even a link on the homepage returns a 502.
> Fix failing build by removing broken mirror in README.rst

- .github/workflows/test_pypy.yml
- .travis.yml
- changelog.d/1020.misc.rst
- tox.ini
As discussed in #1019, here is a PR for migrating the PyPy tests over to GHA.
- Add GHA workflow for PyPy tests
I have used the official Codecov action for coverage reporting, and I think you shouldn’t even need to set the token for it to work. I have also unpinned tox, since it seems to work for these tests. Otherwise I have mostly reused what was already in the other pipelines, with a slight version bump on Postgres.
- Update `tox.ini` to run on Windows
Just added `python -m` before commands.
- Remove PyPy jobs from Travis
Note that I am not running a pypy3.5 test since it’s not installed on the GHA runner.
It would also be nice if you could have a look at whether the warnings for `updatezinfo.py` are expected on macos.
Assuming everything works satisfactory, could I also remove the …
> Migrate PyPy CI to GitHub Actions

- dateutil/easter.py
Easter is a proper noun. 
Fixes https://dateutil.readthedocs.io/en/stable/easter.html
- [n/a] Changes have tests
- [n/a] News fragment added in changelog.d. See [CONTRIBUTING.md](https://github.com/dateutil/dateutil/blob/master/CONTRIBUTING.md#changelog) for details
> Fix Easter typos

- changelog.d/1025.doc.rst
- dateutil/rrule.py
- docs/rrule.rst
The [current documentation](https://dateutil.readthedocs.io/en/latest/rrule.html) on RTD does not display any of the already documented methods in the `rrule` module.
- Added options to automatically document members of `rrule` and `rruleset`
- Used `functools.wraps` on decorator to preserve `__doc__` attribute of `ruleset` methods.
The imports were unintentionally reorganized with `isort` by my editor, but I'd prefer keeping them that way.
> Document methods in `rrule` module

- changelog.d/1024.misc.rst
- dateutil/test/property/test_tz_prop.py
- dateutil/test/test_tz.py
- dateutil/tz/tz.py
- `tz.gettz()` now properly checks for empty string and returns local time
- added test for `tz.gettz()` returning the same result when passed empty string or `None`
`nocache` checks the `gettz(name)` parameter with `if not name` and tries to get the local time from the `TZ` environment variable. When the environment variable does not exist, it only checked for `name is None`, skipping the logic that searches for the local time `tzfile` when passed an empty string.
Closes #925 
Closes #926
> Fix tz.gettz() not returning local time for empty string

- changelog.d/1078.misc.rst
- docs/exercises/index.rst
It seems that relative links to the generated `.html` files doesn't work anymore, so I've replaced them with either `doc` or `mod` references. This should fix that aspect of the CI.
> Fix documentation warning about relative links

- changelog.d/1076.misc.rst
- ci_tools/run_tz_master_env.sh
- dateutil/zoneinfo/rebuild.py
The CI failures are basically manifestations of #1059 (which can be resolved along with #590 when we backport the logic from `zoneinfo`).
I don't want this to continue blocking things and it's a known issue, so I've changed the test to always use the "fat" binaries until #590 is resolved.
> Use "fat" zic binaries in CI tests

- .travis.yml
- AUTHORS.md
- changelog.d/1083.misc.rst
- setup.cfg
Run the tests against Python 3.9 on Travis CI and add the trove classifier for Python 3.9.
3.9.0 final is expected on Monday, 2020-10-05, see https://www.python.org/dev/peps/pep-0596/#schedule
Looks like it's also possible to run the tests against Python 3.9 on appveyor, see https://github.com/appveyor/ci/issues/3467#issuecomment-643534726.  I have no experience with appveyor and maybe it's good enough to wait until appveyor supports Python 3.9 without the workaround via a script?  Please let me know if I should add this.
> Add support for python 3.9

- dateutil/test/test_parser.py
Tests are failing in CI on pypi for windows. The function is returning
an empty string rather than raising. This commit adapts the logic to
skip those cases.
A bug should be reported upstream for pypy for consistency with cpyhton. I think returning an empty string is not expected. I do not have a windows setup to reproduce it though.
Closes
> tests: Fix logic on detecting platform support for `-d`

- AUTHORS.md
- changelog.d/1104.misc.rst
- dateutil/test/test_relativedelta.py
Added two tests to relativedelta to explicitly assert that `relativedelta(day=31)`  returns that last day of the month for February, both for leap years and non-leap years.
Closes [1104](https://github.com/dateutil/dateutil/issues/1104)
> Add two tests for relativedelta(day=31) for February

- changelog.d/1133.misc.rst
- release.py
- requirements-dev.txt
- tox.ini
PEP517 is deprecated, move to `python-build`. This will additionally
validate the build dependencies, enhancing the CI.
Closes
> release: Move to `python-build`

- changelog.d/1060.misc.rst
- dateutil/parser/_parser.py
I believe that the `__init__` method might be simplified in this way. In my opinion, it makes sense to call `decode()` method only on bytes/bytearray objects in both major Pythons.
In Python 2, `bytes` is builtin alias for `str` so `decode()` call does not happen for unicode.
Do you know about any corner case this simplified code is not aware of?
> Call .decode() only for binary data

- .github/workflows/validate.yml
- .travis.yml
Actions are split across multiple jobs to simplify setup and better
represent their intent.
> ci: Move docs, build and tz tox env validation to github actions

- .github/workflows/validate.yml
- tox.ini
We were running tox without enabling isolated environment, this was
therefore resulting in tox not using `pyproject.toml`.
The commit enables isolated environment, and to make it work it also
needs to mark that the building of the tox `.package` env does not have
any dependency. This is needed as otherwise tox will attempt to install
the dependencies in `deps` when building the package as those will be
passed to PEP517, which does not support requirements files.
There you go :). @pganssle do you want me to add a news entry type misc for this kind of changes?
> ci: Remove the need of upgrading pip/setuptools

- changelog.d/975.misc.rst
- setup.cfg
Warehouse now uses the `project_urls` provided to display links in the sidebar, as well as including them in API responses to help automation tool find the source code for dateutil. For example, see Django's [setup.cfg](https://github.com/django/django/blob/master/setup.cfg) and [PyPI listing](https://pypi.org/project/Django/).
> Add GitHub URL for PyPi

- changelog.d/1125.bugfix.rst
- dateutil/parser/isoparser.py
- dateutil/test/test_isoparser.py
Fail when separators are used inconsistently to split the time porting
of a string. Even if more restrictive, we have warned that we were going
to fail on invalid cases of ISO formatted strings. This will prevent
invalid iso formatted strings from being unexpectedly parsed.
This Pr also fixes an xfail that was xfailing due to a typo. IIUC, 201202 is a valid ISO time but not a valid iso date, which is what was intended to be tested.
Closes None
> isoparse: Fail with inconsistent time separators

- dateutil/test/test_internals.py
> migrate away from unittest and adopt pytest for test_internals.py

- dateutil/test/test_parser.py
As suggested by @jbrockmendel I have added a test case for the format in #1029. If you do not think we should support this format feel free to close the issue and this PR.
> Add and xfail unhandled case #1029

- NEWS
- changelog.d/1015.misc.rst
- changelog.d/1017.misc.rst
- changelog.d/1020.misc.rst
- changelog.d/1024.misc.rst
- changelog.d/1025.doc.rst
- changelog.d/1034.data.rst
- changelog.d/1060.misc.rst
- changelog.d/1068.misc.rst
- changelog.d/1076.misc.rst
- changelog.d/1078.misc.rst
- changelog.d/1083.misc.rst
- changelog.d/1104.misc.rst
- changelog.d/1122.bugfix.rst
- changelog.d/1125.bugfix.rst
- changelog.d/1128.data.rst
- changelog.d/1133.misc.rst
- changelog.d/975.misc.rst
- changelog.d/978.misc.rst
- changelog.d/982.misc.rst
- changelog.d/985.doc.rst
- changelog.d/987.bugfix.rst
- changelog.d/990.misc.rst
- changelog.d/991.bugfix.rst
- changelog.d/992.doc.rst
- changelog.d/994.doc.rst
This updates the changelog for the 2.8.1 release.
Relates-to: #1139 
versions.
release from https://www.iana.org/time-zones.
interesting to anyone consuming the package (e.g. changes to CI) with
a reference to the Github PR.
> Prepare 2.8.2 release

- changelog.d/1007.feature.rst
- dateutil/__init__.py
- dateutil/test/test_imports.py
Allow submodule lazy loading for python version3.7+
Addresses #771 using [PEP: 562](https://www.python.org/dev/peps/pep-0562/)
Need help with testing
This is fairly straightforward given the introduction of `__getattr__` for modules. The challenge is testing the import functionality for two subsets of versions: >= 3.7 & < 3.7.
I added what I thought would be reasonable tests if I used tox. Trouble is `import dateutil` loads the submodules regardless of versions - ignoring  `__init__.py `, Which when I think about it maybe is expected behavior.
How to test this bad boy?
> Lazyload submodules python37+

- appveyor.yml
The latest release of virtualenv broke the CI, given that we are
offering limiting support for 3.4 and we plan to drop it in after the
next release, pin the version in CI.
Closes
> ci: Pin virtualenv when running 3.4

- CONTRIBUTING.md
Changed single quotes around `import dateutil; print(dateutil.__version__)` to double quotes, because single quotes do not work in command prompt whereas double quotes do.
Though single and double quote works find in PowerShell and GitBash, single quote in Command Prompt return "SytaxError: EOL while scanning string literal"
I did not take above actions in the checklist because they didn't seem relevant for a minor change to the `contribution.md` file.
> Change single quote to double in dateutil version

- AUTHORS.md
- tests/test_internals.py
Pytest recently deprecated passing `None` as `pytest.warns` argument. As per the documentation [1], new preferred way of ensuring that no warnings are emitted is:
```python
with warnings.catch_warnings():
warnings.simplefilter("error")
```
I verified that this change doesn't work only with the latest Pytest (7.0.0 at this time) but also with much older 4.4.0.
[1] https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests
> Pytest warnings fix

- src/dateutil/parser/isoparser.py
Remove "YYYYMM" from the docs, as it is not actually supported (https://github.com/dateutil/dateutil/issues/251).
To keep it simple, I do not need to be added to AUTHORS.md.
I don't think a docs fix requires a news fragment.
> docs: YYYYMM is not supported

- .github/workflows/validate.yml
- tox.ini
The latest version of ubuntu no longer supports 3.6 or 2.7, so we need to explicitly pin those versions to 20.04
> Update Github Actions configuration for old Pythons

- .github/workflows/validate.yml
- .pre-commit-config.yaml
- README.rst
- pyproject.toml
- src/dateutil/relativedelta.py
- tests/test_isoparser.py
- tox.ini
This creates a `pre-commit` configuration that adds `darken` with `isort` to the pre-commit hooks, and enforces those hooks on GHA.
> Add pre commit

- NEWS
- changelog.d/1346.bugfix.rst
- pyproject.toml
There are some breaking changes, and this is making it so that the `_version.py` file generated is not compatible with Python 2 anymore. I don't see an obvious or easy way to figure out what version of `setuptools_scm` is in use, so we'll just pin the version for now.
I recommend removing `setuptools_scm` entirely in the future.
Closes #1344
> Pin `setuptools_scm` to <8

- .github/workflows/validate.yml
Unsurprisingly, the CI has started to bitrot again.
Looks like the current issues are https://github.com/actions/setup-python/issues/866 and `macos-latest` being an arm runner that does not have support for some older versions of Python.
Codecov was also giving some errors due to rate limiting, so I've made it a soft check, since I am hoping to switch to a [native GHA solution](https://hynek.me/articles/ditch-codecov-python/) anyway.
> Fix bitrot in Github Actions on older Python versions

- .github/workflows/validate.yml
- AUTHORS.md
- changelog.d/1417.misc.rst
- Rearrange test matrix: removed exclude section and moved special cases (older versions) as include entries.
- Switch to macos-13 runners for 3.5-3.7 since macos-12 is no longer available.
- Fix issue with latest codecov action not working on intel macos runners.
- Remove ubuntu-20.04 runners since these are being deprecated soon: https://github.com/actions/runner-images/issues/11101. Instead, test older python versions in python:x.y containers.
> Fix validation workflow

- pyproject.toml
- current version of setuptools (70.1+) does not need wheel at all
- older versions of setuptools would fetch wheel when building wheels (but not sdists)
> Do not require wheel for building
