dateutil/dateutil

dateutil/parser.py

Don't overwrite hours if they exist.

---

dateutil/relativedelta.py
dateutil/test/test.py

This resolves issues #44 and #45.

Relativedelta enhancements - inheritance and weeks property.

---

dateutil/parser.py
dateutil/test/test.py
dateutil/tz.py

These fixes should address #74 and #60.

Changes to tzname and parser unicode/str handling

---

dateutil/zoneinfo/__init__.py
docs/zoneinfo.rst
updatezinfo.py

Add the entire zoneinfo metadata to the tar archive, and add
a function to access it. Also add the metadata to the docs.
Fixes #27  instead of #39

add zoneinfo metadata

---

dateutil/test/test.py

This adds a regression test for issue #100 which has been resolved via #107.

Add test around doing tzset post-initialization

---

.travis.yml
appveyor.yml
dateutil/rrule.py
tox.ini

Test with Python 3.5 on Appveyor, Travis, & Tox

---

dateutil/parser.py
dateutil/test/test.py

fix wrong tokens on unicode string

Fix timelex

---

dateutil/parser.py
dateutil/test/test.py

Thought this was already part of #122.

Add flexibility in subclassing timelex

---

dateutil/parser.py

It seems the docstring was generated as if smart_defaults was True or something like this. At least now the code in the docstring returns year 2047.

Fix doctest string for fuzzy_with_tokens.

---

dateutil/zoneinfo/rebuild.py

This is a fix for minor issue with updatezinfo.py

fix suppressed updatezinfo OSErrors

---

dateutil/rrule.py

Patch based on [an article by Brian Beck](http://blog.brianbeck.com/post/22129050/speeding-up-dateutil-pythons-heapq-module-turns).

use heapq to improve performance

---

.travis.yml
README.rst
appveyor.yml

This adds code coverage analysis to the repository (appveyor and travis). So far we're at a decently respectable ~84%.

Added code coverage on appveyor and Travis.

---

dateutil/rrule.py
dateutil/test/test.py

Maybe I went overkill on the assertion test...

Change warning from error to warning.

---

dateutil/test/test_tz.py
dateutil/tz/win.py

Adjust tzwinlocal repr.

---

dateutil/parser.py
dateutil/test/test.py

Empty string parsing now raises an error.

---

dateutil/relativedelta.py
dateutil/test/test.py

Fixes (mostly) #40.
* Implement explicit fractional support for relative components.
* Add fractions to the repr.
* Deprecate fractional support for absolute components.
* Added .normalize() method to provide integer-only relativedeltas.

Implement explicit fractional support for relativedelta objects.

---

MANIFEST.in

Explicitly include tests in MANIFEST.in

---

NEWS

Makes it nicer to view in the terminal.

NEWS: convert to utf8, remove dos line endings

---

dateutil/test/test.py
dateutil/test/test_easter.py

I also noticed that there's no test for the JULIAN method, but I'm not familiar enough with the Julian calendar to write a test for it.

Move easter tests into their own module, and add one test.

---

NEWS
RELEASING
dateutil/__init__.py

Prepare 2.5.1 release.

---

dateutil/parser.py
dateutil/test/test_parser.py

Fix yearfirst/dayfirst bug.

---

dateutil/parser.py
dateutil/test/test_parser.py

Fixes #233. Should be merged into both 2.5.x branch and the master branch.

Fix issue with parsing unambiguous dates with dayfirst set to True

---

dateutil/test/test_easter.py

This has been bugging me for a while now.

remove trailing whitespace

---

dateutil/tz/tz.py

Added Solaris zoneinfo file location to TZPATHs.

---

dateutil/_common.py
dateutil/relativedelta.py
dateutil/rrule.py
dateutil/tz/tz.py
dateutil/tz/win.py

Fixes #140, more or less. There's still the option to move this and other constants into a `constants` module or something, but there's no need to move too fast on this.

Refactor weekday into common code

---

NEWS
dateutil/__init__.py
setup.py

Prepare 2.6.0 release.

---

dateutil/parser.py

Add :raises TypeError to docstring

---

dateutil/relativedelta.py
dateutil/test/test_relativedelta.py

testing `is not None` instead of truthiness

fixes #346: wrong addition of relativedelta

---

dateutil/relativedelta.py
dateutil/rrule.py

https://www.python.org/dev/peps/pep-0289/
https://docs.python.org/3/reference/expressions.html#generator-expressions

Use generator expressions to avoid creating an unnecessary list in memory

---

dateutil/_common.py
dateutil/relativedelta.py
dateutil/rrule.py
dateutil/test/test_parser.py
dateutil/test/test_tz.py
dateutil/tz/tz.py
dateutil/zoneinfo/__init__.py
dateutil/zoneinfo/rebuild.py

E302 expected 2 blank lines, found X
https://pep8.readthedocs.io/en/latest/intro.html#error-codes

Fix all instances of flake8 E302

---

dateutil/__init__.py
dateutil/_version.py
dateutil/test/test_imports.py
setup.py

Seems like this will be slightly cleaner to manage.

Moved version handling into a separate module.

---

NEWS
release.py

Prepare 2.6.1

---

dateutil/parser.py
dateutil/test/test_parser.py

Fix assert mstridx location; add a test

---

dateutil/parser.py

This is a rebased version of (most of) #425.
Also a couple flake8 fixups.
Some pieces need docstrings.

Get rid of while-loop version of parse_hms

---

dateutil/relativedelta.py
dateutil/test/test_relativedelta.py

fix for https://github.com/dateutil/dateutil/issues/459

fix weeks property getter and add some tests

---

dateutil/tz/tz.py

Fix a dangling parenthesis in tzoffset documentation

---

dateutil/relativedelta.py
dateutil/test/test_relativedelta.py

Add __abs__ to relativedelta

---

dateutil/parser.py
dateutil/test/test_parser.py

Closes #353 
There is one more place where the same valid-hour check should be done, but I'm leaving that until I have a test case ready.

add check for valid hour, with test

---

dateutil/parser.py
dateutil/test/test_parser.py

Add fix for b-Y-d cases; add tests; remove redundant tests

---

dateutil/test/_common.py
dateutil/zoneinfo/__init__.py
setup.py

Remove unused imports

---

dateutil/parser.py
dateutil/test/test_internals.py
dateutil/test/test_parser.py

Will evidently need rebasing after review.

add day check; with test; closes #360

---

.travis.yml
appveyor.yml
setup.py
tox.ini

This changes the test runner over to pytest.

Update test runner to use pytest

---

dateutil/parser.py

pass tzname check to could_be_tzname

---

dateutil/parser.py

Refactor _parse_numeric_token out from the big parsing loop

---

.travis.yml
appveyor.yml
setup.py
test_requirements.txt
tox.ini

Switch over test dependency management to a more centralized `test_requirements.txt`.
HT @mariocj89

Add test requirements

---

dateutil/test/test_parser.py

Adding an expected fail test case for the parser.

---

.travis.yml
appveyor.yml
setup.py

One way to possibly address #507

Fix package discovery in setup.py

---

dateutil/_version.py

This is a temporary solution to #511 until we can get a proper auto-version in place.

Bump version to 2.7.0dev0

---

dateutil/parser/_parser.py
dateutil/test/test_parser.py

Should fix #318 in favor of #319. I don't 100% love special-casing UTC like this, but I think that's the only exception here and anything else would lead to even weirder edge cases.

Fix ambiguous parse

---

setup.py

Update the metadata to reflect authorship vs maintainership

---

AUTHORS.md
LICENSE

Update license with Apache 2.0 and AUTHORS file

---

dateutil/relativedelta.py
dateutil/test/test_relativedelta.py

Fix float handling for years and months in relativedelta

---

README.rst

Change to pytest in README.rst

---

dateutil/rrule.py
dateutil/test/test_rrule.py
dateutil/tz/tz.py

Updated all the links and references from RFC 2445 to RFC 5545
Closes #555

Update link to RFC 2445 / RFC 5545

---

dateutil/tz/tz.py

Takes  tzutc example from the examples section and inserts it into tz.py so that it appears next to the description.

Adds inline example to tzutc class

---

tox.ini

but still fail the test suite if they start passing

xfails do not count towards code coverage

---

AUTHORS.md
dateutil/parser/_parser.py
dateutil/test/test_parser.py

Fixes issue #427 with all tests passing

Fix issue 427

---

AUTHORS.md
dateutil/parser/isoparser.py
dateutil/test/test_isoparser.py

Removed support for YYYYMM

---

appveyor.yml

Related to issue #529 
@gaborbernat Please let me know if the changes I've made are what is expected.

Changed appveyor.yml to reduce tests

---

dateutil/parser/_parser.py

At least we can get something out of the adventure with asv.  We can be fairly confident this is real because we saw cProfile results.

remove min() calls

---

AUTHORS.md
CONTRIBUTING.md
README.rst

Also move building & releasing and testing sections from README to CONTRIBUTING

Add development setup instructions to CONTRIBUTING

---

dateutil/easter.py

This should fix the CI documentation failure.

Fix dead link and cleanup bare links in easter

---

dateutil/test/test_imports.py
dateutil/test/test_tz.py
dateutil/tz/__init__.py
dateutil/tz/tz.py

Closes #339 in favor of #565 and #593.
@Cheukting I had to make a new branch to clean up your git history, which wouldn't have merged cleanly into the master branch as it was. If you make further PRs, it would probably be advisable to delete your fork and make a new one, because I think the master branch is out of sync with the master branch here.

Add resolve_imaginary

---

dateutil/tz/tz.py

Replace dead link with more canonical link.

Update sources for time zone information link

---

dateutil/parser/_parser.py

Available on all supported Python versions.
https://docs.python.org/3/library/functions.html#callable

Prefer builtin callable() over isinstance(..., collections.Callable)

---

README.rst

see https://github.com/gaborbernat/dateutil/blob/badge/README.rst

add readthedocs badge, PyPi versions and license

---

AUTHORS.md
README.rst

Fixes #675.
Duplicate of #676 - I had deleted the forked repo and couldn't update the PR.

Remove duplicate paragraph in README - v2

---

README.rst

Some stragglers raising redirect warnings in the docs builds.

Change over badge pypi links

---

changelog.d/706.doc.rst
dateutil/tz/tz.py

Fixes #702 and does some minor cleanup in tz.py

Cleanup tz docs and PEP8

---

changelog.d/671.doc.rst
dateutil/tz/tz.py

Added examples to the tzfile to the docstring.
Note sure if there was a format you wanted.
Relates to #443

Added examples to tzfile docstring

---

changelog.d/670.doc.rst
docs/examples.rst
docs/relativedelta.rst

Fix links to ISO year week number notation

---

AUTHORS.md
changelog.d/704.doc.rst
dateutil/tz/tz.py
docs/tz.rst

Added parameters, return and examples to gettz.
Closes #647

gettz documentation

---

docs/exercises/index.rst
docs/index.rst

This adds the first few documentation exercises (see #663) to the documentation, specifically #664, #665 and #666. The solutions are not yet posted.
Closes #663

Initial addition of documentation exercises to the documentation

---

AUTHORS.md
changelog.d/740.misc.rst
docs/requirements-docs.txt
tox.ini

Check ReadME.rst is rendered correctly on PyPI.
Closes #734

Check README is Rendered correctly

---

AUTHORS.md
docs/exercises/index.rst

Update index.rst link to parser page

---

AUTHORS.md
changelog.d/760.misc.rst
dateutil/test/test_relativedelta.py

Tested invalid inputs supplied to ``relativedelta.__init__``, and corner cases of ``__add__``.
Contributes to #521

Add tests to take relativedelta.py to 100% coverage

---

AUTHORS.md
changelog.d/758.doc.rst
dateutil/relativedelta.py

Fixing a typo in the relativedelta document page.

Relativedelta doc typo

---

changelog.d/726.doc.rst
dateutil/rrule.py
docs/rrule.rst

Added doc string for _rrulestr
Reformatted docs for rrule module 
Closes #623

#623: added documentation for rrulestr function

---

AUTHORS.md
README.rst

The Readme.rst file now includes the Installation method  
PR for issue #778

Updated the Readme.rst 

---

.travis.yml
changelog.d/785.misc.rst
ci_tools/make_zonefile_metadata.py
ci_tools/run_tz_master_env.sh
dateutil/test/conftest.py
tox.ini
updatezinfo.py

Start testing against master branch of tz project

---

docs/exercises/index.rst
docs/exercises/solutions/mlk-day-rrule.rst
docs/exercises/solutions/mlk_day_rrule_solution.py
setup.cfg

Currently this solution is not automatically tested, but was manually tested using Python 3.6.5.
I think this is a reasonable template for how to get solutions added to the documentation, but I'm wondering if a better approach would be to create a `.py` file that can be automatically run as part of the tests and include it from the tests.
Closes #664

Add solution to Martin Luther King Day exercise

---

changelog.d/839.misc.rst
dateutil/test/test_tz.py

Adding some tests to shore up the coverage

Test fold replace

---

AUTHORS.md
changelog.d/410.feature.rst
dateutil/rrule.py
dateutil/test/test_rrule.py

Quite simply add parameters parsing to EXDATE
Closes #410

Add parameters parsing to EXDATE

---

docs/conf.py

This PR is mainly to test that the new Azure pipelines are set up correctly.

Update copyright notice 2016-2019

---

AUTHORS.md
changelog.d/875.misc.rst
release.py
requirements-dev.txt
setup.cfg

add fix for 2019hackIllinois Use pep517.build in release.py #869

---

README.rst

Add Azure Pipelines badge to readme

add Azure Pipelines badge

---

AUTHORS.md
changelog.d/871.misc.rst
setup.cfg
setup.py

Moved simple constants from setup.py to setup.cfg.
Closes #871

Convert setup.py to declarative build file when possible

---

.travis.yml
changelog.d/876.misc.rst
tox.ini

Fix the add a build job in tox #870

---

AUTHORS.md
azure-pipelines.yml

Add PyPy and PyPy3 coverage on Windows to Azure Pipelines.
Closes #451 
- [NA] Changes have tests
- [NA] News fragment added in changelog.d. See [CONTRIBUTING.md](https://github.com/dateutil/dateutil/blob/master/CONTRIBUTING.md#changelog) for details

add PyPy versions on Windows

---

AUTHORS.md
changelog.d/893.misc.rst
dateutil/test/_common.py
dateutil/test/test_tz.py

Fix tests if not TZ change allowed

---

AUTHORS.md
changelog.d/985.doc.rst
dateutil/utils.py

Fix simple typo: negilible -> negligible
Closes #985

Fix simple typo: negilible -> negligible

---

.travis.yml
requirements-dev.txt

ci: Fix 3.4 test runs

---

changelog.d/978.misc.rst
dateutil/test/test_imports.py
dateutil/test/test_utils.py

Closes https://github.com/dateutil/dateutil/pull/976

Migrate away from unittest and adopt pytest

---

dateutil/rrule.py

Fix typo discovered by codespell

---

changelog.d/1284.bugfix.rst
src/dateutil/tz/tz.py

avoid deprecated utcfromtimestamp

---

.github/workflows/validate.yml

use python-is-python2 for py2.7

---

changelog.d/1342.data.rst
zonefile_metadata.json

Hopefully one of the last times I'll have to do this — update the embedded zoneinfo tarball JSON file.

Update zonefile_metadata to 2024a

---

.github/workflows/publish.yml
MANIFEST.in
NEWS
changelog.d/1007.feature.rst
changelog.d/1167.doc.rst
changelog.d/1174.misc.rst
changelog.d/1211.misc.rst
changelog.d/1284.bugfix.rst
changelog.d/1286.misc.rst
changelog.d/1342.data.rst
setup.cfg
tox.ini

Prepare a release for version 2.9.0
Closes #1314

Release 2.9.0

---

AUTHORS.md
changelog.d/1424.bugfix.rst
setup.cfg

Bump six version to fix the issue. see [comment](https://github.com/dateutil/dateutil/issues/1415#issuecomment-2773772196)
Closes   #1416

Fix: bump six version
